/*
 * Generated by gen-yagl-calls.py, do not modify!
 */
#include "GL/gl.h"
#include "yagl_host_gles_calls.h"
#include "yagl_transport_gl.h"
#include "yagl_state.h"
#include <assert.h>

/*
 * glDrawArrays wrapper. id = 1
 */
void yagl_host_glDrawArrays(GLenum mode, GLint first, GLsizei count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 1, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, mode);
    yagl_transport_put_out_GLint(t, first);
    yagl_transport_put_out_GLsizei(t, count);
    yagl_transport_end(t);
}

/*
 * glDrawElements wrapper. id = 2
 */
void yagl_host_glDrawElements(GLenum mode, GLsizei count, GLenum type, const GLvoid *indices, int32_t indices_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 2, 5 * 8, 3 * 8 + yagl_transport_array_size(indices, indices_count, 1));
    yagl_transport_put_out_GLenum(t, mode);
    yagl_transport_put_out_GLsizei(t, count);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_out_array(t, indices, indices_count, 1);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(indices, indices_count * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glReadPixels wrapper. id = 3
 */
void yagl_host_glReadPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels, int32_t pixels_maxcount, int32_t *pixels_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 3, 8 * 8, 6 * 8 + yagl_transport_array_size(pixels, pixels_maxcount, 1));
    yagl_transport_put_out_GLint(t, x);
    yagl_transport_put_out_GLint(t, y);
    yagl_transport_put_out_GLsizei(t, width);
    yagl_transport_put_out_GLsizei(t, height);
    yagl_transport_put_out_GLenum(t, format);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_in_array(t, pixels, pixels_maxcount, pixels_count, 1);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(pixels, pixels_maxcount * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGenVertexArrays wrapper. id = 4
 */
void yagl_host_glGenVertexArrays(const GLuint *arrays, int32_t arrays_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 4, 2 * 8, 0 * 8 + yagl_transport_array_size(arrays, arrays_count, sizeof(GLuint)));
    yagl_transport_put_out_array(t, arrays, arrays_count, sizeof(GLuint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(arrays, arrays_count * sizeof(GLuint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glBindVertexArray wrapper. id = 5
 */
void yagl_host_glBindVertexArray(GLuint array)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 5, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLuint(t, array);
    yagl_transport_end(t);
}

/*
 * glDisableVertexAttribArray wrapper. id = 6
 */
void yagl_host_glDisableVertexAttribArray(GLuint index)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 6, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLuint(t, index);
    yagl_transport_end(t);
}

/*
 * glEnableVertexAttribArray wrapper. id = 7
 */
void yagl_host_glEnableVertexAttribArray(GLuint index)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 7, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLuint(t, index);
    yagl_transport_end(t);
}

/*
 * glVertexAttribPointerData wrapper. id = 8
 */
void yagl_host_glVertexAttribPointerData(GLuint indx, GLint size, GLenum type, GLboolean normalized, GLsizei stride, GLint first, const GLvoid *data, int32_t data_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 8, 8 * 8, 6 * 8 + yagl_transport_array_size(data, data_count, 1));
    yagl_transport_put_out_GLuint(t, indx);
    yagl_transport_put_out_GLint(t, size);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_out_GLboolean(t, normalized);
    yagl_transport_put_out_GLsizei(t, stride);
    yagl_transport_put_out_GLint(t, first);
    yagl_transport_put_out_array(t, data, data_count, 1);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(data, data_count * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glVertexAttribPointerOffset wrapper. id = 9
 */
void yagl_host_glVertexAttribPointerOffset(GLuint indx, GLint size, GLenum type, GLboolean normalized, GLsizei stride, GLsizei offset)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 9, 6 * 8, 6 * 8);
    yagl_transport_put_out_GLuint(t, indx);
    yagl_transport_put_out_GLint(t, size);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_out_GLboolean(t, normalized);
    yagl_transport_put_out_GLsizei(t, stride);
    yagl_transport_put_out_GLsizei(t, offset);
    yagl_transport_end(t);
}

/*
 * glVertexPointerData wrapper. id = 10
 */
void yagl_host_glVertexPointerData(GLint size, GLenum type, GLsizei stride, GLint first, const GLvoid *data, int32_t data_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 10, 6 * 8, 4 * 8 + yagl_transport_array_size(data, data_count, 1));
    yagl_transport_put_out_GLint(t, size);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_out_GLsizei(t, stride);
    yagl_transport_put_out_GLint(t, first);
    yagl_transport_put_out_array(t, data, data_count, 1);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(data, data_count * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glVertexPointerOffset wrapper. id = 11
 */
void yagl_host_glVertexPointerOffset(GLint size, GLenum type, GLsizei stride, GLsizei offset)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 11, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLint(t, size);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_out_GLsizei(t, stride);
    yagl_transport_put_out_GLsizei(t, offset);
    yagl_transport_end(t);
}

/*
 * glNormalPointerData wrapper. id = 12
 */
void yagl_host_glNormalPointerData(GLenum type, GLsizei stride, GLint first, const GLvoid *data, int32_t data_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 12, 5 * 8, 3 * 8 + yagl_transport_array_size(data, data_count, 1));
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_out_GLsizei(t, stride);
    yagl_transport_put_out_GLint(t, first);
    yagl_transport_put_out_array(t, data, data_count, 1);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(data, data_count * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glNormalPointerOffset wrapper. id = 13
 */
void yagl_host_glNormalPointerOffset(GLenum type, GLsizei stride, GLsizei offset)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 13, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_out_GLsizei(t, stride);
    yagl_transport_put_out_GLsizei(t, offset);
    yagl_transport_end(t);
}

/*
 * glColorPointerData wrapper. id = 14
 */
void yagl_host_glColorPointerData(GLint size, GLenum type, GLsizei stride, GLint first, const GLvoid *data, int32_t data_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 14, 6 * 8, 4 * 8 + yagl_transport_array_size(data, data_count, 1));
    yagl_transport_put_out_GLint(t, size);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_out_GLsizei(t, stride);
    yagl_transport_put_out_GLint(t, first);
    yagl_transport_put_out_array(t, data, data_count, 1);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(data, data_count * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glColorPointerOffset wrapper. id = 15
 */
void yagl_host_glColorPointerOffset(GLint size, GLenum type, GLsizei stride, GLsizei offset)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 15, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLint(t, size);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_out_GLsizei(t, stride);
    yagl_transport_put_out_GLsizei(t, offset);
    yagl_transport_end(t);
}

/*
 * glTexCoordPointerData wrapper. id = 16
 */
void yagl_host_glTexCoordPointerData(GLint tex_id, GLint size, GLenum type, GLsizei stride, GLint first, const GLvoid *data, int32_t data_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 16, 7 * 8, 5 * 8 + yagl_transport_array_size(data, data_count, 1));
    yagl_transport_put_out_GLint(t, tex_id);
    yagl_transport_put_out_GLint(t, size);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_out_GLsizei(t, stride);
    yagl_transport_put_out_GLint(t, first);
    yagl_transport_put_out_array(t, data, data_count, 1);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(data, data_count * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glTexCoordPointerOffset wrapper. id = 17
 */
void yagl_host_glTexCoordPointerOffset(GLint size, GLenum type, GLsizei stride, GLsizei offset)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 17, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLint(t, size);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_out_GLsizei(t, stride);
    yagl_transport_put_out_GLsizei(t, offset);
    yagl_transport_end(t);
}

/*
 * glDisableClientState wrapper. id = 18
 */
void yagl_host_glDisableClientState(GLenum array)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 18, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, array);
    yagl_transport_end(t);
}

/*
 * glEnableClientState wrapper. id = 19
 */
void yagl_host_glEnableClientState(GLenum array)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 19, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, array);
    yagl_transport_end(t);
}

/*
 * glGenBuffers wrapper. id = 20
 */
void yagl_host_glGenBuffers(const GLuint *buffers, int32_t buffers_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 20, 2 * 8, 0 * 8 + yagl_transport_array_size(buffers, buffers_count, sizeof(GLuint)));
    yagl_transport_put_out_array(t, buffers, buffers_count, sizeof(GLuint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(buffers, buffers_count * sizeof(GLuint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glBindBuffer wrapper. id = 21
 */
void yagl_host_glBindBuffer(GLenum target, GLuint buffer)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 21, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLuint(t, buffer);
    yagl_transport_end(t);
}

/*
 * glBufferData wrapper. id = 22
 */
void yagl_host_glBufferData(GLenum target, const GLvoid *data, int32_t data_count, GLenum usage)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 22, 4 * 8, 2 * 8 + yagl_transport_array_size(data, data_count, 1));
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_array(t, data, data_count, 1);
    yagl_transport_put_out_GLenum(t, usage);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(data, data_count * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glBufferSubData wrapper. id = 23
 */
void yagl_host_glBufferSubData(GLenum target, GLsizei offset, const GLvoid *data, int32_t data_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 23, 4 * 8, 2 * 8 + yagl_transport_array_size(data, data_count, 1));
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLsizei(t, offset);
    yagl_transport_put_out_array(t, data, data_count, 1);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(data, data_count * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGenTextures wrapper. id = 24
 */
void yagl_host_glGenTextures(const GLuint *textures, int32_t textures_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 24, 2 * 8, 0 * 8 + yagl_transport_array_size(textures, textures_count, sizeof(GLuint)));
    yagl_transport_put_out_array(t, textures, textures_count, sizeof(GLuint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(textures, textures_count * sizeof(GLuint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glBindTexture wrapper. id = 25
 */
void yagl_host_glBindTexture(GLenum target, GLuint texture)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 25, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLuint(t, texture);
    yagl_transport_end(t);
}

/*
 * glActiveTexture wrapper. id = 26
 */
void yagl_host_glActiveTexture(GLenum texture)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 26, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, texture);
    yagl_transport_end(t);
}

/*
 * glCompressedTexImage2D wrapper. id = 27
 */
void yagl_host_glCompressedTexImage2D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, const GLvoid *data, int32_t data_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 27, 8 * 8, 6 * 8 + yagl_transport_array_size(data, data_count, 1));
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLint(t, level);
    yagl_transport_put_out_GLenum(t, internalformat);
    yagl_transport_put_out_GLsizei(t, width);
    yagl_transport_put_out_GLsizei(t, height);
    yagl_transport_put_out_GLint(t, border);
    yagl_transport_put_out_array(t, data, data_count, 1);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(data, data_count * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glCompressedTexSubImage2D wrapper. id = 28
 */
void yagl_host_glCompressedTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, const GLvoid *data, int32_t data_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 28, 9 * 8, 7 * 8 + yagl_transport_array_size(data, data_count, 1));
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLint(t, level);
    yagl_transport_put_out_GLint(t, xoffset);
    yagl_transport_put_out_GLint(t, yoffset);
    yagl_transport_put_out_GLsizei(t, width);
    yagl_transport_put_out_GLsizei(t, height);
    yagl_transport_put_out_GLenum(t, format);
    yagl_transport_put_out_array(t, data, data_count, 1);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(data, data_count * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glCopyTexImage2D wrapper. id = 29
 */
void yagl_host_glCopyTexImage2D(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 29, 8 * 8, 8 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLint(t, level);
    yagl_transport_put_out_GLenum(t, internalformat);
    yagl_transport_put_out_GLint(t, x);
    yagl_transport_put_out_GLint(t, y);
    yagl_transport_put_out_GLsizei(t, width);
    yagl_transport_put_out_GLsizei(t, height);
    yagl_transport_put_out_GLint(t, border);
    yagl_transport_end(t);
}

/*
 * glCopyTexSubImage2D wrapper. id = 30
 */
void yagl_host_glCopyTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 30, 8 * 8, 8 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLint(t, level);
    yagl_transport_put_out_GLint(t, xoffset);
    yagl_transport_put_out_GLint(t, yoffset);
    yagl_transport_put_out_GLint(t, x);
    yagl_transport_put_out_GLint(t, y);
    yagl_transport_put_out_GLsizei(t, width);
    yagl_transport_put_out_GLsizei(t, height);
    yagl_transport_end(t);
}

/*
 * glGetTexParameterfv wrapper. id = 31
 */
void yagl_host_glGetTexParameterfv(GLenum target, GLenum pname, GLfloat *param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 31, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_GLfloat(t, param);
    yagl_transport_end(t);
}

/*
 * glGetTexParameteriv wrapper. id = 32
 */
void yagl_host_glGetTexParameteriv(GLenum target, GLenum pname, GLint *param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 32, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_GLint(t, param);
    yagl_transport_end(t);
}

/*
 * glTexImage2D wrapper. id = 33
 */
void yagl_host_glTexImage2D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels, int32_t pixels_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 33, 10 * 8, 8 * 8 + yagl_transport_array_size(pixels, pixels_count, 1));
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLint(t, level);
    yagl_transport_put_out_GLint(t, internalformat);
    yagl_transport_put_out_GLsizei(t, width);
    yagl_transport_put_out_GLsizei(t, height);
    yagl_transport_put_out_GLint(t, border);
    yagl_transport_put_out_GLenum(t, format);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_out_array(t, pixels, pixels_count, 1);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(pixels, pixels_count * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glTexParameterf wrapper. id = 34
 */
void yagl_host_glTexParameterf(GLenum target, GLenum pname, GLfloat param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 34, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_GLfloat(t, param);
    yagl_transport_end(t);
}

/*
 * glTexParameterfv wrapper. id = 35
 */
void yagl_host_glTexParameterfv(GLenum target, GLenum pname, const GLfloat *params, int32_t params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 35, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_array(t, params, params_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(params, params_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glTexParameteri wrapper. id = 36
 */
void yagl_host_glTexParameteri(GLenum target, GLenum pname, GLint param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 36, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_GLint(t, param);
    yagl_transport_end(t);
}

/*
 * glTexParameteriv wrapper. id = 37
 */
void yagl_host_glTexParameteriv(GLenum target, GLenum pname, const GLint *params, int32_t params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 37, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_count, sizeof(GLint)));
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_array(t, params, params_count, sizeof(GLint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(params, params_count * sizeof(GLint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glTexSubImage2D wrapper. id = 38
 */
void yagl_host_glTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels, int32_t pixels_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 38, 10 * 8, 8 * 8 + yagl_transport_array_size(pixels, pixels_count, 1));
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLint(t, level);
    yagl_transport_put_out_GLint(t, xoffset);
    yagl_transport_put_out_GLint(t, yoffset);
    yagl_transport_put_out_GLsizei(t, width);
    yagl_transport_put_out_GLsizei(t, height);
    yagl_transport_put_out_GLenum(t, format);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_out_array(t, pixels, pixels_count, 1);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(pixels, pixels_count * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glClientActiveTexture wrapper. id = 39
 */
void yagl_host_glClientActiveTexture(GLenum texture)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 39, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, texture);
    yagl_transport_end(t);
}

/*
 * glTexEnvi wrapper. id = 40
 */
void yagl_host_glTexEnvi(GLenum target, GLenum pname, GLint param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 40, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_GLint(t, param);
    yagl_transport_end(t);
}

/*
 * glTexEnvf wrapper. id = 41
 */
void yagl_host_glTexEnvf(GLenum target, GLenum pname, GLfloat param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 41, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_GLfloat(t, param);
    yagl_transport_end(t);
}

/*
 * glMultiTexCoord4f wrapper. id = 42
 */
void yagl_host_glMultiTexCoord4f(GLenum target, GLfloat s, GLfloat tt, GLfloat r, GLfloat q)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 42, 5 * 8, 5 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLfloat(t, s);
    yagl_transport_put_out_GLfloat(t, tt);
    yagl_transport_put_out_GLfloat(t, r);
    yagl_transport_put_out_GLfloat(t, q);
    yagl_transport_end(t);
}

/*
 * glTexEnviv wrapper. id = 43
 */
void yagl_host_glTexEnviv(GLenum target, GLenum pname, const GLint *params, int32_t params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 43, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_count, sizeof(GLint)));
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_array(t, params, params_count, sizeof(GLint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(params, params_count * sizeof(GLint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glTexEnvfv wrapper. id = 44
 */
void yagl_host_glTexEnvfv(GLenum target, GLenum pname, const GLfloat *params, int32_t params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 44, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_array(t, params, params_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(params, params_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetTexEnviv wrapper. id = 45
 */
void yagl_host_glGetTexEnviv(GLenum env, GLenum pname, GLint *params, int32_t params_maxcount, int32_t *params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 45, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_maxcount, sizeof(GLint)));
    yagl_transport_put_out_GLenum(t, env);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_array(t, params, params_maxcount, params_count, sizeof(GLint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(params, params_maxcount * sizeof(GLint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetTexEnvfv wrapper. id = 46
 */
void yagl_host_glGetTexEnvfv(GLenum env, GLenum pname, GLfloat *params, int32_t params_maxcount, int32_t *params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 46, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_maxcount, sizeof(GLfloat)));
    yagl_transport_put_out_GLenum(t, env);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_array(t, params, params_maxcount, params_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(params, params_maxcount * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGenFramebuffers wrapper. id = 47
 */
void yagl_host_glGenFramebuffers(const GLuint *framebuffers, int32_t framebuffers_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 47, 2 * 8, 0 * 8 + yagl_transport_array_size(framebuffers, framebuffers_count, sizeof(GLuint)));
    yagl_transport_put_out_array(t, framebuffers, framebuffers_count, sizeof(GLuint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(framebuffers, framebuffers_count * sizeof(GLuint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glBindFramebuffer wrapper. id = 48
 */
void yagl_host_glBindFramebuffer(GLenum target, GLuint framebuffer)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 48, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLuint(t, framebuffer);
    yagl_transport_end(t);
}

/*
 * glFramebufferTexture2D wrapper. id = 49
 */
void yagl_host_glFramebufferTexture2D(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 49, 5 * 8, 5 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, attachment);
    yagl_transport_put_out_GLenum(t, textarget);
    yagl_transport_put_out_GLuint(t, texture);
    yagl_transport_put_out_GLint(t, level);
    yagl_transport_end(t);
}

/*
 * glFramebufferRenderbuffer wrapper. id = 50
 */
void yagl_host_glFramebufferRenderbuffer(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 50, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, attachment);
    yagl_transport_put_out_GLenum(t, renderbuffertarget);
    yagl_transport_put_out_GLuint(t, renderbuffer);
    yagl_transport_end(t);
}

/*
 * glBlitFramebuffer wrapper. id = 51
 */
void yagl_host_glBlitFramebuffer(GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 51, 10 * 8, 10 * 8);
    yagl_transport_put_out_GLint(t, srcX0);
    yagl_transport_put_out_GLint(t, srcY0);
    yagl_transport_put_out_GLint(t, srcX1);
    yagl_transport_put_out_GLint(t, srcY1);
    yagl_transport_put_out_GLint(t, dstX0);
    yagl_transport_put_out_GLint(t, dstY0);
    yagl_transport_put_out_GLint(t, dstX1);
    yagl_transport_put_out_GLint(t, dstY1);
    yagl_transport_put_out_GLbitfield(t, mask);
    yagl_transport_put_out_GLenum(t, filter);
    yagl_transport_end(t);
}

/*
 * glDrawBuffers wrapper. id = 52
 */
void yagl_host_glDrawBuffers(const GLenum *bufs, int32_t bufs_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 52, 2 * 8, 0 * 8 + yagl_transport_array_size(bufs, bufs_count, sizeof(GLenum)));
    yagl_transport_put_out_array(t, bufs, bufs_count, sizeof(GLenum));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(bufs, bufs_count * sizeof(GLenum));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGenRenderbuffers wrapper. id = 53
 */
void yagl_host_glGenRenderbuffers(const GLuint *renderbuffers, int32_t renderbuffers_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 53, 2 * 8, 0 * 8 + yagl_transport_array_size(renderbuffers, renderbuffers_count, sizeof(GLuint)));
    yagl_transport_put_out_array(t, renderbuffers, renderbuffers_count, sizeof(GLuint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(renderbuffers, renderbuffers_count * sizeof(GLuint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glBindRenderbuffer wrapper. id = 54
 */
void yagl_host_glBindRenderbuffer(GLenum target, GLuint renderbuffer)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 54, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLuint(t, renderbuffer);
    yagl_transport_end(t);
}

/*
 * glRenderbufferStorage wrapper. id = 55
 */
void yagl_host_glRenderbufferStorage(GLenum target, GLenum internalformat, GLsizei width, GLsizei height)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 55, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, internalformat);
    yagl_transport_put_out_GLsizei(t, width);
    yagl_transport_put_out_GLsizei(t, height);
    yagl_transport_end(t);
}

/*
 * glGetRenderbufferParameteriv wrapper. id = 56
 */
void yagl_host_glGetRenderbufferParameteriv(GLenum target, GLenum pname, GLint *param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 56, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_GLint(t, param);
    yagl_transport_end(t);
}

/*
 * glCreateProgram wrapper. id = 57
 */
void yagl_host_glCreateProgram(GLuint program)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 57, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_end(t);
}

/*
 * glCreateShader wrapper. id = 58
 */
void yagl_host_glCreateShader(GLuint shader, GLenum type)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 58, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLuint(t, shader);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_end(t);
}

/*
 * glShaderSource wrapper. id = 59
 */
void yagl_host_glShaderSource(GLuint shader, const GLchar *string, int32_t string_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 59, 3 * 8, 1 * 8 + yagl_transport_array_size(string, string_count, sizeof(GLchar)));
    yagl_transport_put_out_GLuint(t, shader);
    yagl_transport_put_out_array(t, string, string_count, sizeof(GLchar));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(string, string_count * sizeof(GLchar));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glAttachShader wrapper. id = 60
 */
void yagl_host_glAttachShader(GLuint program, GLuint shader)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 60, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_put_out_GLuint(t, shader);
    yagl_transport_end(t);
}

/*
 * glDetachShader wrapper. id = 61
 */
void yagl_host_glDetachShader(GLuint program, GLuint shader)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 61, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_put_out_GLuint(t, shader);
    yagl_transport_end(t);
}

/*
 * glCompileShader wrapper. id = 62
 */
void yagl_host_glCompileShader(GLuint shader)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 62, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLuint(t, shader);
    yagl_transport_end(t);
}

/*
 * glBindAttribLocation wrapper. id = 63
 */
void yagl_host_glBindAttribLocation(GLuint program, GLuint index, const GLchar *name, int32_t name_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 63, 4 * 8, 2 * 8 + yagl_transport_array_size(name, name_count, sizeof(GLchar)));
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_put_out_GLuint(t, index);
    yagl_transport_put_out_array(t, name, name_count, sizeof(GLchar));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(name, name_count * sizeof(GLchar));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetActiveAttrib wrapper. id = 64
 */
void yagl_host_glGetActiveAttrib(GLuint program, GLuint index, GLint *size, GLenum *type, GLchar *name, int32_t name_maxcount, int32_t *name_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 64, 8 * 8, 6 * 8 + yagl_transport_array_size(name, name_maxcount, sizeof(GLchar)));
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_put_out_GLuint(t, index);
    yagl_transport_put_in_GLint(t, size);
    yagl_transport_put_in_GLenum(t, type);
    yagl_transport_put_in_array(t, name, name_maxcount, name_count, sizeof(GLchar));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(name, name_maxcount * sizeof(GLchar));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetActiveUniform wrapper. id = 65
 */
void yagl_host_glGetActiveUniform(GLuint program, GLuint index, GLint *size, GLenum *type, GLchar *name, int32_t name_maxcount, int32_t *name_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 65, 8 * 8, 6 * 8 + yagl_transport_array_size(name, name_maxcount, sizeof(GLchar)));
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_put_out_GLuint(t, index);
    yagl_transport_put_in_GLint(t, size);
    yagl_transport_put_in_GLenum(t, type);
    yagl_transport_put_in_array(t, name, name_maxcount, name_count, sizeof(GLchar));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(name, name_maxcount * sizeof(GLchar));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetAttribLocation wrapper. id = 66
 */
int yagl_host_glGetAttribLocation(GLuint program, const GLchar *name, int32_t name_count)
{
    struct yagl_transport *t = yagl_get_transport();
    int retval;

    yagl_transport_begin(t, yagl_api_id_gles, 66, 5 * 8, 3 * 8 + yagl_transport_array_size(name, name_count, sizeof(GLchar)));
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_put_out_array(t, name, name_count, sizeof(GLchar));
    yagl_transport_put_in_int(t, &retval);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(name, name_count * sizeof(GLchar));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }

    return retval;
}

/*
 * glGetProgramiv wrapper. id = 67
 */
void yagl_host_glGetProgramiv(GLuint program, GLenum pname, GLint *param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 67, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_GLint(t, param);
    yagl_transport_end(t);
}

/*
 * glGetProgramInfoLog wrapper. id = 68
 */
GLboolean yagl_host_glGetProgramInfoLog(GLuint program, GLchar *infolog, int32_t infolog_maxcount, int32_t *infolog_count)
{
    struct yagl_transport *t = yagl_get_transport();
    GLboolean retval;

    yagl_transport_begin(t, yagl_api_id_gles, 68, 5 * 8, 3 * 8 + yagl_transport_array_size(infolog, infolog_maxcount, sizeof(GLchar)));
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_put_in_array(t, infolog, infolog_maxcount, infolog_count, sizeof(GLchar));
    yagl_transport_put_in_GLboolean(t, &retval);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(infolog, infolog_maxcount * sizeof(GLchar));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }

    return retval;
}

/*
 * glGetShaderiv wrapper. id = 69
 */
void yagl_host_glGetShaderiv(GLuint shader, GLenum pname, GLint *param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 69, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLuint(t, shader);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_GLint(t, param);
    yagl_transport_end(t);
}

/*
 * glGetShaderInfoLog wrapper. id = 70
 */
GLboolean yagl_host_glGetShaderInfoLog(GLuint shader, GLchar *infolog, int32_t infolog_maxcount, int32_t *infolog_count)
{
    struct yagl_transport *t = yagl_get_transport();
    GLboolean retval;

    yagl_transport_begin(t, yagl_api_id_gles, 70, 5 * 8, 3 * 8 + yagl_transport_array_size(infolog, infolog_maxcount, sizeof(GLchar)));
    yagl_transport_put_out_GLuint(t, shader);
    yagl_transport_put_in_array(t, infolog, infolog_maxcount, infolog_count, sizeof(GLchar));
    yagl_transport_put_in_GLboolean(t, &retval);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(infolog, infolog_maxcount * sizeof(GLchar));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }

    return retval;
}

/*
 * glGetUniformfv wrapper. id = 71
 */
void yagl_host_glGetUniformfv(GLboolean tl, GLuint program, uint32_t location, GLfloat *params, int32_t params_maxcount, int32_t *params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 71, 5 * 8, 3 * 8 + yagl_transport_array_size(params, params_maxcount, sizeof(GLfloat)));
    yagl_transport_put_out_GLboolean(t, tl);
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_put_out_uint32_t(t, location);
    yagl_transport_put_in_array(t, params, params_maxcount, params_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(params, params_maxcount * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetUniformiv wrapper. id = 72
 */
void yagl_host_glGetUniformiv(GLboolean tl, GLuint program, uint32_t location, GLint *params, int32_t params_maxcount, int32_t *params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 72, 5 * 8, 3 * 8 + yagl_transport_array_size(params, params_maxcount, sizeof(GLint)));
    yagl_transport_put_out_GLboolean(t, tl);
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_put_out_uint32_t(t, location);
    yagl_transport_put_in_array(t, params, params_maxcount, params_count, sizeof(GLint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(params, params_maxcount * sizeof(GLint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetUniformLocation wrapper. id = 73
 */
int yagl_host_glGetUniformLocation(GLuint program, const GLchar *name, int32_t name_count)
{
    struct yagl_transport *t = yagl_get_transport();
    int retval;

    yagl_transport_begin(t, yagl_api_id_gles, 73, 5 * 8, 3 * 8 + yagl_transport_array_size(name, name_count, sizeof(GLchar)));
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_put_out_array(t, name, name_count, sizeof(GLchar));
    yagl_transport_put_in_int(t, &retval);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(name, name_count * sizeof(GLchar));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }

    return retval;
}

/*
 * glGetVertexAttribfv wrapper. id = 74
 */
void yagl_host_glGetVertexAttribfv(GLuint index, GLenum pname, GLfloat *params, int32_t params_maxcount, int32_t *params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 74, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_maxcount, sizeof(GLfloat)));
    yagl_transport_put_out_GLuint(t, index);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_array(t, params, params_maxcount, params_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(params, params_maxcount * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetVertexAttribiv wrapper. id = 75
 */
void yagl_host_glGetVertexAttribiv(GLuint index, GLenum pname, GLint *params, int32_t params_maxcount, int32_t *params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 75, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_maxcount, sizeof(GLint)));
    yagl_transport_put_out_GLuint(t, index);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_array(t, params, params_maxcount, params_count, sizeof(GLint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(params, params_maxcount * sizeof(GLint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glLinkProgram wrapper. id = 76
 */
void yagl_host_glLinkProgram(GLuint program, GLint *params, int32_t params_maxcount, int32_t *params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 76, 3 * 8, 1 * 8 + yagl_transport_array_size(params, params_maxcount, sizeof(GLint)));
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_put_in_array(t, params, params_maxcount, params_count, sizeof(GLint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(params, params_maxcount * sizeof(GLint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glUniform1f wrapper. id = 77
 */
void yagl_host_glUniform1f(GLboolean tl, uint32_t location, GLfloat x)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 77, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLboolean(t, tl);
    yagl_transport_put_out_uint32_t(t, location);
    yagl_transport_put_out_GLfloat(t, x);
    yagl_transport_end(t);
}

/*
 * glUniform1fv wrapper. id = 78
 */
void yagl_host_glUniform1fv(GLboolean tl, uint32_t location, const GLfloat *v, int32_t v_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 78, 4 * 8, 2 * 8 + yagl_transport_array_size(v, v_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLboolean(t, tl);
    yagl_transport_put_out_uint32_t(t, location);
    yagl_transport_put_out_array(t, v, v_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(v, v_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glUniform1i wrapper. id = 79
 */
void yagl_host_glUniform1i(GLboolean tl, uint32_t location, GLint x)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 79, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLboolean(t, tl);
    yagl_transport_put_out_uint32_t(t, location);
    yagl_transport_put_out_GLint(t, x);
    yagl_transport_end(t);
}

/*
 * glUniform1iv wrapper. id = 80
 */
void yagl_host_glUniform1iv(GLboolean tl, uint32_t location, const GLint *v, int32_t v_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 80, 4 * 8, 2 * 8 + yagl_transport_array_size(v, v_count, sizeof(GLint)));
    yagl_transport_put_out_GLboolean(t, tl);
    yagl_transport_put_out_uint32_t(t, location);
    yagl_transport_put_out_array(t, v, v_count, sizeof(GLint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(v, v_count * sizeof(GLint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glUniform2f wrapper. id = 81
 */
void yagl_host_glUniform2f(GLboolean tl, uint32_t location, GLfloat x, GLfloat y)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 81, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLboolean(t, tl);
    yagl_transport_put_out_uint32_t(t, location);
    yagl_transport_put_out_GLfloat(t, x);
    yagl_transport_put_out_GLfloat(t, y);
    yagl_transport_end(t);
}

/*
 * glUniform2fv wrapper. id = 82
 */
void yagl_host_glUniform2fv(GLboolean tl, uint32_t location, const GLfloat *v, int32_t v_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 82, 4 * 8, 2 * 8 + yagl_transport_array_size(v, v_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLboolean(t, tl);
    yagl_transport_put_out_uint32_t(t, location);
    yagl_transport_put_out_array(t, v, v_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(v, v_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glUniform2i wrapper. id = 83
 */
void yagl_host_glUniform2i(GLboolean tl, uint32_t location, GLint x, GLint y)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 83, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLboolean(t, tl);
    yagl_transport_put_out_uint32_t(t, location);
    yagl_transport_put_out_GLint(t, x);
    yagl_transport_put_out_GLint(t, y);
    yagl_transport_end(t);
}

/*
 * glUniform2iv wrapper. id = 84
 */
void yagl_host_glUniform2iv(GLboolean tl, uint32_t location, const GLint *v, int32_t v_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 84, 4 * 8, 2 * 8 + yagl_transport_array_size(v, v_count, sizeof(GLint)));
    yagl_transport_put_out_GLboolean(t, tl);
    yagl_transport_put_out_uint32_t(t, location);
    yagl_transport_put_out_array(t, v, v_count, sizeof(GLint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(v, v_count * sizeof(GLint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glUniform3f wrapper. id = 85
 */
void yagl_host_glUniform3f(GLboolean tl, uint32_t location, GLfloat x, GLfloat y, GLfloat z)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 85, 5 * 8, 5 * 8);
    yagl_transport_put_out_GLboolean(t, tl);
    yagl_transport_put_out_uint32_t(t, location);
    yagl_transport_put_out_GLfloat(t, x);
    yagl_transport_put_out_GLfloat(t, y);
    yagl_transport_put_out_GLfloat(t, z);
    yagl_transport_end(t);
}

/*
 * glUniform3fv wrapper. id = 86
 */
void yagl_host_glUniform3fv(GLboolean tl, uint32_t location, const GLfloat *v, int32_t v_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 86, 4 * 8, 2 * 8 + yagl_transport_array_size(v, v_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLboolean(t, tl);
    yagl_transport_put_out_uint32_t(t, location);
    yagl_transport_put_out_array(t, v, v_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(v, v_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glUniform3i wrapper. id = 87
 */
void yagl_host_glUniform3i(GLboolean tl, uint32_t location, GLint x, GLint y, GLint z)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 87, 5 * 8, 5 * 8);
    yagl_transport_put_out_GLboolean(t, tl);
    yagl_transport_put_out_uint32_t(t, location);
    yagl_transport_put_out_GLint(t, x);
    yagl_transport_put_out_GLint(t, y);
    yagl_transport_put_out_GLint(t, z);
    yagl_transport_end(t);
}

/*
 * glUniform3iv wrapper. id = 88
 */
void yagl_host_glUniform3iv(GLboolean tl, uint32_t location, const GLint *v, int32_t v_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 88, 4 * 8, 2 * 8 + yagl_transport_array_size(v, v_count, sizeof(GLint)));
    yagl_transport_put_out_GLboolean(t, tl);
    yagl_transport_put_out_uint32_t(t, location);
    yagl_transport_put_out_array(t, v, v_count, sizeof(GLint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(v, v_count * sizeof(GLint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glUniform4f wrapper. id = 89
 */
void yagl_host_glUniform4f(GLboolean tl, uint32_t location, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 89, 6 * 8, 6 * 8);
    yagl_transport_put_out_GLboolean(t, tl);
    yagl_transport_put_out_uint32_t(t, location);
    yagl_transport_put_out_GLfloat(t, x);
    yagl_transport_put_out_GLfloat(t, y);
    yagl_transport_put_out_GLfloat(t, z);
    yagl_transport_put_out_GLfloat(t, w);
    yagl_transport_end(t);
}

/*
 * glUniform4fv wrapper. id = 90
 */
void yagl_host_glUniform4fv(GLboolean tl, uint32_t location, const GLfloat *v, int32_t v_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 90, 4 * 8, 2 * 8 + yagl_transport_array_size(v, v_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLboolean(t, tl);
    yagl_transport_put_out_uint32_t(t, location);
    yagl_transport_put_out_array(t, v, v_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(v, v_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glUniform4i wrapper. id = 91
 */
void yagl_host_glUniform4i(GLboolean tl, uint32_t location, GLint x, GLint y, GLint z, GLint w)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 91, 6 * 8, 6 * 8);
    yagl_transport_put_out_GLboolean(t, tl);
    yagl_transport_put_out_uint32_t(t, location);
    yagl_transport_put_out_GLint(t, x);
    yagl_transport_put_out_GLint(t, y);
    yagl_transport_put_out_GLint(t, z);
    yagl_transport_put_out_GLint(t, w);
    yagl_transport_end(t);
}

/*
 * glUniform4iv wrapper. id = 92
 */
void yagl_host_glUniform4iv(GLboolean tl, uint32_t location, const GLint *v, int32_t v_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 92, 4 * 8, 2 * 8 + yagl_transport_array_size(v, v_count, sizeof(GLint)));
    yagl_transport_put_out_GLboolean(t, tl);
    yagl_transport_put_out_uint32_t(t, location);
    yagl_transport_put_out_array(t, v, v_count, sizeof(GLint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(v, v_count * sizeof(GLint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glUniformMatrix2fv wrapper. id = 93
 */
void yagl_host_glUniformMatrix2fv(GLboolean tl, uint32_t location, GLboolean transpose, const GLfloat *value, int32_t value_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 93, 5 * 8, 3 * 8 + yagl_transport_array_size(value, value_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLboolean(t, tl);
    yagl_transport_put_out_uint32_t(t, location);
    yagl_transport_put_out_GLboolean(t, transpose);
    yagl_transport_put_out_array(t, value, value_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(value, value_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glUniformMatrix3fv wrapper. id = 94
 */
void yagl_host_glUniformMatrix3fv(GLboolean tl, uint32_t location, GLboolean transpose, const GLfloat *value, int32_t value_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 94, 5 * 8, 3 * 8 + yagl_transport_array_size(value, value_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLboolean(t, tl);
    yagl_transport_put_out_uint32_t(t, location);
    yagl_transport_put_out_GLboolean(t, transpose);
    yagl_transport_put_out_array(t, value, value_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(value, value_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glUniformMatrix4fv wrapper. id = 95
 */
void yagl_host_glUniformMatrix4fv(GLboolean tl, uint32_t location, GLboolean transpose, const GLfloat *value, int32_t value_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 95, 5 * 8, 3 * 8 + yagl_transport_array_size(value, value_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLboolean(t, tl);
    yagl_transport_put_out_uint32_t(t, location);
    yagl_transport_put_out_GLboolean(t, transpose);
    yagl_transport_put_out_array(t, value, value_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(value, value_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glUseProgram wrapper. id = 96
 */
void yagl_host_glUseProgram(GLuint program)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 96, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_end(t);
}

/*
 * glValidateProgram wrapper. id = 97
 */
void yagl_host_glValidateProgram(GLuint program)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 97, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_end(t);
}

/*
 * glVertexAttrib1f wrapper. id = 98
 */
void yagl_host_glVertexAttrib1f(GLuint indx, GLfloat x)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 98, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLuint(t, indx);
    yagl_transport_put_out_GLfloat(t, x);
    yagl_transport_end(t);
}

/*
 * glVertexAttrib1fv wrapper. id = 99
 */
void yagl_host_glVertexAttrib1fv(GLuint indx, const GLfloat *values, int32_t values_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 99, 3 * 8, 1 * 8 + yagl_transport_array_size(values, values_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLuint(t, indx);
    yagl_transport_put_out_array(t, values, values_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(values, values_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glVertexAttrib2f wrapper. id = 100
 */
void yagl_host_glVertexAttrib2f(GLuint indx, GLfloat x, GLfloat y)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 100, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLuint(t, indx);
    yagl_transport_put_out_GLfloat(t, x);
    yagl_transport_put_out_GLfloat(t, y);
    yagl_transport_end(t);
}

/*
 * glVertexAttrib2fv wrapper. id = 101
 */
void yagl_host_glVertexAttrib2fv(GLuint indx, const GLfloat *values, int32_t values_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 101, 3 * 8, 1 * 8 + yagl_transport_array_size(values, values_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLuint(t, indx);
    yagl_transport_put_out_array(t, values, values_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(values, values_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glVertexAttrib3f wrapper. id = 102
 */
void yagl_host_glVertexAttrib3f(GLuint indx, GLfloat x, GLfloat y, GLfloat z)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 102, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLuint(t, indx);
    yagl_transport_put_out_GLfloat(t, x);
    yagl_transport_put_out_GLfloat(t, y);
    yagl_transport_put_out_GLfloat(t, z);
    yagl_transport_end(t);
}

/*
 * glVertexAttrib3fv wrapper. id = 103
 */
void yagl_host_glVertexAttrib3fv(GLuint indx, const GLfloat *values, int32_t values_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 103, 3 * 8, 1 * 8 + yagl_transport_array_size(values, values_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLuint(t, indx);
    yagl_transport_put_out_array(t, values, values_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(values, values_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glVertexAttrib4f wrapper. id = 104
 */
void yagl_host_glVertexAttrib4f(GLuint indx, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 104, 5 * 8, 5 * 8);
    yagl_transport_put_out_GLuint(t, indx);
    yagl_transport_put_out_GLfloat(t, x);
    yagl_transport_put_out_GLfloat(t, y);
    yagl_transport_put_out_GLfloat(t, z);
    yagl_transport_put_out_GLfloat(t, w);
    yagl_transport_end(t);
}

/*
 * glVertexAttrib4fv wrapper. id = 105
 */
void yagl_host_glVertexAttrib4fv(GLuint indx, const GLfloat *values, int32_t values_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 105, 3 * 8, 1 * 8 + yagl_transport_array_size(values, values_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLuint(t, indx);
    yagl_transport_put_out_array(t, values, values_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(values, values_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetActiveUniformsiv wrapper. id = 106
 */
void yagl_host_glGetActiveUniformsiv(GLuint program, const GLuint *uniformIndices, int32_t uniformIndices_count, GLint *params, int32_t params_maxcount, int32_t *params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 106, 5 * 8, 1 * 8 + yagl_transport_array_size(uniformIndices, uniformIndices_count, sizeof(GLuint)) + yagl_transport_array_size(params, params_maxcount, sizeof(GLint)));
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_put_out_array(t, uniformIndices, uniformIndices_count, sizeof(GLuint));
    yagl_transport_put_in_array(t, params, params_maxcount, params_count, sizeof(GLint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(uniformIndices, uniformIndices_count * sizeof(GLuint));
            yagl_transport_probe_write(params, params_maxcount * sizeof(GLint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetIntegerv wrapper. id = 107
 */
void yagl_host_glGetIntegerv(GLenum pname, GLint *params, int32_t params_maxcount, int32_t *params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 107, 3 * 8, 1 * 8 + yagl_transport_array_size(params, params_maxcount, sizeof(GLint)));
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_array(t, params, params_maxcount, params_count, sizeof(GLint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(params, params_maxcount * sizeof(GLint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetFloatv wrapper. id = 108
 */
void yagl_host_glGetFloatv(GLenum pname, GLfloat *params, int32_t params_maxcount, int32_t *params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 108, 3 * 8, 1 * 8 + yagl_transport_array_size(params, params_maxcount, sizeof(GLfloat)));
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_array(t, params, params_maxcount, params_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(params, params_maxcount * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetString wrapper. id = 109
 */
void yagl_host_glGetString(GLenum name, GLchar *str, int32_t str_maxcount, int32_t *str_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 109, 3 * 8, 1 * 8 + yagl_transport_array_size(str, str_maxcount, sizeof(GLchar)));
    yagl_transport_put_out_GLenum(t, name);
    yagl_transport_put_in_array(t, str, str_maxcount, str_count, sizeof(GLchar));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(str, str_maxcount * sizeof(GLchar));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glIsEnabled wrapper. id = 110
 */
GLboolean yagl_host_glIsEnabled(GLenum cap)
{
    struct yagl_transport *t = yagl_get_transport();
    GLboolean retval;

    yagl_transport_begin(t, yagl_api_id_gles, 110, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, cap);
    yagl_transport_put_in_GLboolean(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * glDeleteObjects wrapper. id = 111
 */
void yagl_host_glDeleteObjects(const GLuint *objects, int32_t objects_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 111, 2 * 8, 0 * 8 + yagl_transport_array_size(objects, objects_count, sizeof(GLuint)));
    yagl_transport_put_out_array(t, objects, objects_count, sizeof(GLuint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(objects, objects_count * sizeof(GLuint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glBlendEquation wrapper. id = 112
 */
void yagl_host_glBlendEquation(GLenum mode)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 112, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, mode);
    yagl_transport_end(t);
}

/*
 * glBlendEquationSeparate wrapper. id = 113
 */
void yagl_host_glBlendEquationSeparate(GLenum modeRGB, GLenum modeAlpha)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 113, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, modeRGB);
    yagl_transport_put_out_GLenum(t, modeAlpha);
    yagl_transport_end(t);
}

/*
 * glBlendFunc wrapper. id = 114
 */
void yagl_host_glBlendFunc(GLenum sfactor, GLenum dfactor)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 114, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, sfactor);
    yagl_transport_put_out_GLenum(t, dfactor);
    yagl_transport_end(t);
}

/*
 * glBlendFuncSeparate wrapper. id = 115
 */
void yagl_host_glBlendFuncSeparate(GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 115, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLenum(t, srcRGB);
    yagl_transport_put_out_GLenum(t, dstRGB);
    yagl_transport_put_out_GLenum(t, srcAlpha);
    yagl_transport_put_out_GLenum(t, dstAlpha);
    yagl_transport_end(t);
}

/*
 * glBlendColor wrapper. id = 116
 */
void yagl_host_glBlendColor(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 116, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLclampf(t, red);
    yagl_transport_put_out_GLclampf(t, green);
    yagl_transport_put_out_GLclampf(t, blue);
    yagl_transport_put_out_GLclampf(t, alpha);
    yagl_transport_end(t);
}

/*
 * glClear wrapper. id = 117
 */
void yagl_host_glClear(GLbitfield mask)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 117, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLbitfield(t, mask);
    yagl_transport_end(t);
}

/*
 * glClearColor wrapper. id = 118
 */
void yagl_host_glClearColor(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 118, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLclampf(t, red);
    yagl_transport_put_out_GLclampf(t, green);
    yagl_transport_put_out_GLclampf(t, blue);
    yagl_transport_put_out_GLclampf(t, alpha);
    yagl_transport_end(t);
}

/*
 * glClearDepthf wrapper. id = 119
 */
void yagl_host_glClearDepthf(GLclampf depth)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 119, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLclampf(t, depth);
    yagl_transport_end(t);
}

/*
 * glClearStencil wrapper. id = 120
 */
void yagl_host_glClearStencil(GLint s)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 120, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLint(t, s);
    yagl_transport_end(t);
}

/*
 * glColorMask wrapper. id = 121
 */
void yagl_host_glColorMask(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 121, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLboolean(t, red);
    yagl_transport_put_out_GLboolean(t, green);
    yagl_transport_put_out_GLboolean(t, blue);
    yagl_transport_put_out_GLboolean(t, alpha);
    yagl_transport_end(t);
}

/*
 * glCullFace wrapper. id = 122
 */
void yagl_host_glCullFace(GLenum mode)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 122, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, mode);
    yagl_transport_end(t);
}

/*
 * glDepthFunc wrapper. id = 123
 */
void yagl_host_glDepthFunc(GLenum func)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 123, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, func);
    yagl_transport_end(t);
}

/*
 * glDepthMask wrapper. id = 124
 */
void yagl_host_glDepthMask(GLboolean flag)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 124, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLboolean(t, flag);
    yagl_transport_end(t);
}

/*
 * glDepthRangef wrapper. id = 125
 */
void yagl_host_glDepthRangef(GLclampf zNear, GLclampf zFar)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 125, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLclampf(t, zNear);
    yagl_transport_put_out_GLclampf(t, zFar);
    yagl_transport_end(t);
}

/*
 * glEnable wrapper. id = 126
 */
void yagl_host_glEnable(GLenum cap)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 126, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, cap);
    yagl_transport_end(t);
}

/*
 * glDisable wrapper. id = 127
 */
void yagl_host_glDisable(GLenum cap)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 127, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, cap);
    yagl_transport_end(t);
}

/*
 * glFlush wrapper. id = 128
 */
void yagl_host_glFlush()
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 128, 0 * 8, 0 * 8);
    yagl_transport_end(t);
    yagl_transport_sync(t);
}

/*
 * glFrontFace wrapper. id = 129
 */
void yagl_host_glFrontFace(GLenum mode)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 129, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, mode);
    yagl_transport_end(t);
}

/*
 * glGenerateMipmap wrapper. id = 130
 */
void yagl_host_glGenerateMipmap(GLenum target)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 130, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_end(t);
}

/*
 * glHint wrapper. id = 131
 */
void yagl_host_glHint(GLenum target, GLenum mode)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 131, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, mode);
    yagl_transport_end(t);
}

/*
 * glLineWidth wrapper. id = 132
 */
void yagl_host_glLineWidth(GLfloat width)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 132, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLfloat(t, width);
    yagl_transport_end(t);
}

/*
 * glPixelStorei wrapper. id = 133
 */
void yagl_host_glPixelStorei(GLenum pname, GLint param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 133, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_GLint(t, param);
    yagl_transport_end(t);
}

/*
 * glPolygonOffset wrapper. id = 134
 */
void yagl_host_glPolygonOffset(GLfloat factor, GLfloat units)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 134, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLfloat(t, factor);
    yagl_transport_put_out_GLfloat(t, units);
    yagl_transport_end(t);
}

/*
 * glScissor wrapper. id = 135
 */
void yagl_host_glScissor(GLint x, GLint y, GLsizei width, GLsizei height)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 135, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLint(t, x);
    yagl_transport_put_out_GLint(t, y);
    yagl_transport_put_out_GLsizei(t, width);
    yagl_transport_put_out_GLsizei(t, height);
    yagl_transport_end(t);
}

/*
 * glStencilFunc wrapper. id = 136
 */
void yagl_host_glStencilFunc(GLenum func, GLint ref, GLuint mask)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 136, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, func);
    yagl_transport_put_out_GLint(t, ref);
    yagl_transport_put_out_GLuint(t, mask);
    yagl_transport_end(t);
}

/*
 * glStencilMask wrapper. id = 137
 */
void yagl_host_glStencilMask(GLuint mask)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 137, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLuint(t, mask);
    yagl_transport_end(t);
}

/*
 * glStencilOp wrapper. id = 138
 */
void yagl_host_glStencilOp(GLenum fail, GLenum zfail, GLenum zpass)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 138, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, fail);
    yagl_transport_put_out_GLenum(t, zfail);
    yagl_transport_put_out_GLenum(t, zpass);
    yagl_transport_end(t);
}

/*
 * glSampleCoverage wrapper. id = 139
 */
void yagl_host_glSampleCoverage(GLclampf value, GLboolean invert)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 139, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLclampf(t, value);
    yagl_transport_put_out_GLboolean(t, invert);
    yagl_transport_end(t);
}

/*
 * glViewport wrapper. id = 140
 */
void yagl_host_glViewport(GLint x, GLint y, GLsizei width, GLsizei height)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 140, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLint(t, x);
    yagl_transport_put_out_GLint(t, y);
    yagl_transport_put_out_GLsizei(t, width);
    yagl_transport_put_out_GLsizei(t, height);
    yagl_transport_end(t);
}

/*
 * glStencilFuncSeparate wrapper. id = 141
 */
void yagl_host_glStencilFuncSeparate(GLenum face, GLenum func, GLint ref, GLuint mask)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 141, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLenum(t, face);
    yagl_transport_put_out_GLenum(t, func);
    yagl_transport_put_out_GLint(t, ref);
    yagl_transport_put_out_GLuint(t, mask);
    yagl_transport_end(t);
}

/*
 * glStencilMaskSeparate wrapper. id = 142
 */
void yagl_host_glStencilMaskSeparate(GLenum face, GLuint mask)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 142, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, face);
    yagl_transport_put_out_GLuint(t, mask);
    yagl_transport_end(t);
}

/*
 * glStencilOpSeparate wrapper. id = 143
 */
void yagl_host_glStencilOpSeparate(GLenum face, GLenum fail, GLenum zfail, GLenum zpass)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 143, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLenum(t, face);
    yagl_transport_put_out_GLenum(t, fail);
    yagl_transport_put_out_GLenum(t, zfail);
    yagl_transport_put_out_GLenum(t, zpass);
    yagl_transport_end(t);
}

/*
 * glPointSize wrapper. id = 144
 */
void yagl_host_glPointSize(GLfloat size)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 144, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLfloat(t, size);
    yagl_transport_end(t);
}

/*
 * glAlphaFunc wrapper. id = 145
 */
void yagl_host_glAlphaFunc(GLenum func, GLclampf ref)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 145, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, func);
    yagl_transport_put_out_GLclampf(t, ref);
    yagl_transport_end(t);
}

/*
 * glMatrixMode wrapper. id = 146
 */
void yagl_host_glMatrixMode(GLenum mode)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 146, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, mode);
    yagl_transport_end(t);
}

/*
 * glLoadIdentity wrapper. id = 147
 */
void yagl_host_glLoadIdentity()
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 147, 0 * 8, 0 * 8);
    yagl_transport_end(t);
}

/*
 * glPopMatrix wrapper. id = 148
 */
void yagl_host_glPopMatrix()
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 148, 0 * 8, 0 * 8);
    yagl_transport_end(t);
}

/*
 * glPushMatrix wrapper. id = 149
 */
void yagl_host_glPushMatrix()
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 149, 0 * 8, 0 * 8);
    yagl_transport_end(t);
}

/*
 * glRotatef wrapper. id = 150
 */
void yagl_host_glRotatef(GLfloat angle, GLfloat x, GLfloat y, GLfloat z)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 150, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLfloat(t, angle);
    yagl_transport_put_out_GLfloat(t, x);
    yagl_transport_put_out_GLfloat(t, y);
    yagl_transport_put_out_GLfloat(t, z);
    yagl_transport_end(t);
}

/*
 * glTranslatef wrapper. id = 151
 */
void yagl_host_glTranslatef(GLfloat x, GLfloat y, GLfloat z)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 151, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLfloat(t, x);
    yagl_transport_put_out_GLfloat(t, y);
    yagl_transport_put_out_GLfloat(t, z);
    yagl_transport_end(t);
}

/*
 * glScalef wrapper. id = 152
 */
void yagl_host_glScalef(GLfloat x, GLfloat y, GLfloat z)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 152, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLfloat(t, x);
    yagl_transport_put_out_GLfloat(t, y);
    yagl_transport_put_out_GLfloat(t, z);
    yagl_transport_end(t);
}

/*
 * glOrthof wrapper. id = 153
 */
void yagl_host_glOrthof(GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 153, 6 * 8, 6 * 8);
    yagl_transport_put_out_GLfloat(t, left);
    yagl_transport_put_out_GLfloat(t, right);
    yagl_transport_put_out_GLfloat(t, bottom);
    yagl_transport_put_out_GLfloat(t, top);
    yagl_transport_put_out_GLfloat(t, zNear);
    yagl_transport_put_out_GLfloat(t, zFar);
    yagl_transport_end(t);
}

/*
 * glColor4f wrapper. id = 154
 */
void yagl_host_glColor4f(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 154, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLfloat(t, red);
    yagl_transport_put_out_GLfloat(t, green);
    yagl_transport_put_out_GLfloat(t, blue);
    yagl_transport_put_out_GLfloat(t, alpha);
    yagl_transport_end(t);
}

/*
 * glColor4ub wrapper. id = 155
 */
void yagl_host_glColor4ub(GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 155, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLubyte(t, red);
    yagl_transport_put_out_GLubyte(t, green);
    yagl_transport_put_out_GLubyte(t, blue);
    yagl_transport_put_out_GLubyte(t, alpha);
    yagl_transport_end(t);
}

/*
 * glNormal3f wrapper. id = 156
 */
void yagl_host_glNormal3f(GLfloat nx, GLfloat ny, GLfloat nz)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 156, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLfloat(t, nx);
    yagl_transport_put_out_GLfloat(t, ny);
    yagl_transport_put_out_GLfloat(t, nz);
    yagl_transport_end(t);
}

/*
 * glPointParameterf wrapper. id = 157
 */
void yagl_host_glPointParameterf(GLenum pname, GLfloat param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 157, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_GLfloat(t, param);
    yagl_transport_end(t);
}

/*
 * glPointParameterfv wrapper. id = 158
 */
void yagl_host_glPointParameterfv(GLenum pname, const GLfloat *params, int32_t params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 158, 3 * 8, 1 * 8 + yagl_transport_array_size(params, params_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_array(t, params, params_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(params, params_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glFogf wrapper. id = 159
 */
void yagl_host_glFogf(GLenum pname, GLfloat param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 159, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_GLfloat(t, param);
    yagl_transport_end(t);
}

/*
 * glFogfv wrapper. id = 160
 */
void yagl_host_glFogfv(GLenum pname, const GLfloat *params, int32_t params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 160, 3 * 8, 1 * 8 + yagl_transport_array_size(params, params_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_array(t, params, params_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(params, params_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glFrustumf wrapper. id = 161
 */
void yagl_host_glFrustumf(GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 161, 6 * 8, 6 * 8);
    yagl_transport_put_out_GLfloat(t, left);
    yagl_transport_put_out_GLfloat(t, right);
    yagl_transport_put_out_GLfloat(t, bottom);
    yagl_transport_put_out_GLfloat(t, top);
    yagl_transport_put_out_GLfloat(t, zNear);
    yagl_transport_put_out_GLfloat(t, zFar);
    yagl_transport_end(t);
}

/*
 * glLightf wrapper. id = 162
 */
void yagl_host_glLightf(GLenum light, GLenum pname, GLfloat param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 162, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, light);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_GLfloat(t, param);
    yagl_transport_end(t);
}

/*
 * glLightfv wrapper. id = 163
 */
void yagl_host_glLightfv(GLenum light, GLenum pname, const GLfloat *params, int32_t params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 163, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLenum(t, light);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_array(t, params, params_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(params, params_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetLightfv wrapper. id = 164
 */
void yagl_host_glGetLightfv(GLenum light, GLenum pname, GLfloat *params, int32_t params_maxcount, int32_t *params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 164, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_maxcount, sizeof(GLfloat)));
    yagl_transport_put_out_GLenum(t, light);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_array(t, params, params_maxcount, params_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(params, params_maxcount * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glLightModelf wrapper. id = 165
 */
void yagl_host_glLightModelf(GLenum pname, GLfloat param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 165, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_GLfloat(t, param);
    yagl_transport_end(t);
}

/*
 * glLightModelfv wrapper. id = 166
 */
void yagl_host_glLightModelfv(GLenum pname, const GLfloat *params, int32_t params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 166, 3 * 8, 1 * 8 + yagl_transport_array_size(params, params_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_array(t, params, params_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(params, params_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glMaterialf wrapper. id = 167
 */
void yagl_host_glMaterialf(GLenum face, GLenum pname, GLfloat param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 167, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, face);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_GLfloat(t, param);
    yagl_transport_end(t);
}

/*
 * glMaterialfv wrapper. id = 168
 */
void yagl_host_glMaterialfv(GLenum face, GLenum pname, const GLfloat *params, int32_t params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 168, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLenum(t, face);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_array(t, params, params_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(params, params_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetMaterialfv wrapper. id = 169
 */
void yagl_host_glGetMaterialfv(GLenum face, GLenum pname, GLfloat *params, int32_t params_maxcount, int32_t *params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 169, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_maxcount, sizeof(GLfloat)));
    yagl_transport_put_out_GLenum(t, face);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_array(t, params, params_maxcount, params_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(params, params_maxcount * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glShadeModel wrapper. id = 170
 */
void yagl_host_glShadeModel(GLenum mode)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 170, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, mode);
    yagl_transport_end(t);
}

/*
 * glLogicOp wrapper. id = 171
 */
void yagl_host_glLogicOp(GLenum opcode)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 171, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, opcode);
    yagl_transport_end(t);
}

/*
 * glMultMatrixf wrapper. id = 172
 */
void yagl_host_glMultMatrixf(const GLfloat *m, int32_t m_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 172, 2 * 8, 0 * 8 + yagl_transport_array_size(m, m_count, sizeof(GLfloat)));
    yagl_transport_put_out_array(t, m, m_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(m, m_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glLoadMatrixf wrapper. id = 173
 */
void yagl_host_glLoadMatrixf(const GLfloat *m, int32_t m_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 173, 2 * 8, 0 * 8 + yagl_transport_array_size(m, m_count, sizeof(GLfloat)));
    yagl_transport_put_out_array(t, m, m_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(m, m_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glClipPlanef wrapper. id = 174
 */
void yagl_host_glClipPlanef(GLenum plane, const GLfloat *equation, int32_t equation_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 174, 3 * 8, 1 * 8 + yagl_transport_array_size(equation, equation_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLenum(t, plane);
    yagl_transport_put_out_array(t, equation, equation_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(equation, equation_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetClipPlanef wrapper. id = 175
 */
void yagl_host_glGetClipPlanef(GLenum pname, GLfloat *eqn, int32_t eqn_maxcount, int32_t *eqn_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 175, 3 * 8, 1 * 8 + yagl_transport_array_size(eqn, eqn_maxcount, sizeof(GLfloat)));
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_array(t, eqn, eqn_maxcount, eqn_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(eqn, eqn_maxcount * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glUpdateOffscreenImageYAGL wrapper. id = 176
 */
void yagl_host_glUpdateOffscreenImageYAGL(GLuint texture, uint32_t width, uint32_t height, uint32_t bpp, const void *pixels, int32_t pixels_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 176, 6 * 8, 4 * 8 + yagl_transport_array_size(pixels, pixels_count, 1));
    yagl_transport_put_out_GLuint(t, texture);
    yagl_transport_put_out_uint32_t(t, width);
    yagl_transport_put_out_uint32_t(t, height);
    yagl_transport_put_out_uint32_t(t, bpp);
    yagl_transport_put_out_array(t, pixels, pixels_count, 1);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(pixels, pixels_count * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGenUniformLocationYAGL wrapper. id = 177
 */
void yagl_host_glGenUniformLocationYAGL(uint32_t location, GLuint program, const GLchar *name, int32_t name_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 177, 4 * 8, 2 * 8 + yagl_transport_array_size(name, name_count, sizeof(GLchar)));
    yagl_transport_put_out_uint32_t(t, location);
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_put_out_array(t, name, name_count, sizeof(GLchar));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(name, name_count * sizeof(GLchar));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glDeleteUniformLocationsYAGL wrapper. id = 178
 */
void yagl_host_glDeleteUniformLocationsYAGL(const uint32_t *locations, int32_t locations_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles, 178, 2 * 8, 0 * 8 + yagl_transport_array_size(locations, locations_count, sizeof(uint32_t)));
    yagl_transport_put_out_array(t, locations, locations_count, sizeof(uint32_t));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(locations, locations_count * sizeof(uint32_t));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}
