/*
 * Generated by gen-yagl-calls.py, do not modify!
 */
#include "yagl_host_gles1_calls.h"
#include "yagl_transport_gl1.h"
#include "yagl_state.h"
#include <assert.h>

/*
 * glActiveTexture wrapper. id = 1
 */
void yagl_host_glActiveTexture(GLenum texture)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 1, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, texture);
    yagl_transport_end(t);
}

/*
 * glBindBuffer wrapper. id = 2
 */
void yagl_host_glBindBuffer(GLenum target, GLuint buffer)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 2, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLuint(t, buffer);
    yagl_transport_end(t);
}

/*
 * glBindFramebuffer wrapper. id = 3
 */
void yagl_host_glBindFramebuffer(GLenum target, GLuint framebuffer)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 3, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLuint(t, framebuffer);
    yagl_transport_end(t);
}

/*
 * glBindRenderbuffer wrapper. id = 4
 */
void yagl_host_glBindRenderbuffer(GLenum target, GLuint renderbuffer)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 4, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLuint(t, renderbuffer);
    yagl_transport_end(t);
}

/*
 * glBindTexture wrapper. id = 5
 */
void yagl_host_glBindTexture(GLenum target, GLuint texture)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 5, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLuint(t, texture);
    yagl_transport_end(t);
}

/*
 * glBlendEquation wrapper. id = 6
 */
void yagl_host_glBlendEquation(GLenum mode)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 6, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, mode);
    yagl_transport_end(t);
}

/*
 * glBlendEquationSeparate wrapper. id = 7
 */
void yagl_host_glBlendEquationSeparate(GLenum modeRGB, GLenum modeAlpha)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 7, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, modeRGB);
    yagl_transport_put_out_GLenum(t, modeAlpha);
    yagl_transport_end(t);
}

/*
 * glBlendFunc wrapper. id = 8
 */
void yagl_host_glBlendFunc(GLenum sfactor, GLenum dfactor)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 8, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, sfactor);
    yagl_transport_put_out_GLenum(t, dfactor);
    yagl_transport_end(t);
}

/*
 * glBlendFuncSeparate wrapper. id = 9
 */
void yagl_host_glBlendFuncSeparate(GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 9, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLenum(t, srcRGB);
    yagl_transport_put_out_GLenum(t, dstRGB);
    yagl_transport_put_out_GLenum(t, srcAlpha);
    yagl_transport_put_out_GLenum(t, dstAlpha);
    yagl_transport_end(t);
}

/*
 * glBufferData wrapper. id = 10
 */
void yagl_host_glBufferData(GLenum target, const GLvoid *data, int32_t data_count, GLenum usage)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 10, 4 * 8, 2 * 8 + yagl_transport_array_size(data, data_count, 1));
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_array(t, data, data_count, 1);
    yagl_transport_put_out_GLenum(t, usage);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(data, data_count * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glBufferSubData wrapper. id = 11
 */
void yagl_host_glBufferSubData(GLenum target, GLsizei offset, const GLvoid *data, int32_t data_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 11, 4 * 8, 2 * 8 + yagl_transport_array_size(data, data_count, 1));
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLsizei(t, offset);
    yagl_transport_put_out_array(t, data, data_count, 1);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(data, data_count * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glCheckFramebufferStatus wrapper. id = 12
 */
GLenum yagl_host_glCheckFramebufferStatus(GLenum target)
{
    struct yagl_transport *t = yagl_get_transport();
    GLenum retval;

    yagl_transport_begin(t, yagl_api_id_gles1, 12, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_in_GLenum(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * glClear wrapper. id = 13
 */
void yagl_host_glClear(GLbitfield mask)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 13, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLbitfield(t, mask);
    yagl_transport_end(t);
}

/*
 * glClearColor wrapper. id = 14
 */
void yagl_host_glClearColor(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 14, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLclampf(t, red);
    yagl_transport_put_out_GLclampf(t, green);
    yagl_transport_put_out_GLclampf(t, blue);
    yagl_transport_put_out_GLclampf(t, alpha);
    yagl_transport_end(t);
}

/*
 * glClearDepthf wrapper. id = 15
 */
void yagl_host_glClearDepthf(GLclampf depth)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 15, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLclampf(t, depth);
    yagl_transport_end(t);
}

/*
 * glClearStencil wrapper. id = 16
 */
void yagl_host_glClearStencil(GLint s)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 16, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLint(t, s);
    yagl_transport_end(t);
}

/*
 * glColorMask wrapper. id = 17
 */
void yagl_host_glColorMask(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 17, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLboolean(t, red);
    yagl_transport_put_out_GLboolean(t, green);
    yagl_transport_put_out_GLboolean(t, blue);
    yagl_transport_put_out_GLboolean(t, alpha);
    yagl_transport_end(t);
}

/*
 * glCompressedTexImage2D wrapper. id = 18
 */
void yagl_host_glCompressedTexImage2D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, const GLvoid *data, int32_t data_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 18, 8 * 8, 6 * 8 + yagl_transport_array_size(data, data_count, 1));
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLint(t, level);
    yagl_transport_put_out_GLenum(t, internalformat);
    yagl_transport_put_out_GLsizei(t, width);
    yagl_transport_put_out_GLsizei(t, height);
    yagl_transport_put_out_GLint(t, border);
    yagl_transport_put_out_array(t, data, data_count, 1);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(data, data_count * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glCompressedTexSubImage2D wrapper. id = 19
 */
void yagl_host_glCompressedTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, const GLvoid *data, int32_t data_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 19, 9 * 8, 7 * 8 + yagl_transport_array_size(data, data_count, 1));
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLint(t, level);
    yagl_transport_put_out_GLint(t, xoffset);
    yagl_transport_put_out_GLint(t, yoffset);
    yagl_transport_put_out_GLsizei(t, width);
    yagl_transport_put_out_GLsizei(t, height);
    yagl_transport_put_out_GLenum(t, format);
    yagl_transport_put_out_array(t, data, data_count, 1);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(data, data_count * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glCopyTexImage2D wrapper. id = 20
 */
void yagl_host_glCopyTexImage2D(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 20, 8 * 8, 8 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLint(t, level);
    yagl_transport_put_out_GLenum(t, internalformat);
    yagl_transport_put_out_GLint(t, x);
    yagl_transport_put_out_GLint(t, y);
    yagl_transport_put_out_GLsizei(t, width);
    yagl_transport_put_out_GLsizei(t, height);
    yagl_transport_put_out_GLint(t, border);
    yagl_transport_end(t);
}

/*
 * glCopyTexSubImage2D wrapper. id = 21
 */
void yagl_host_glCopyTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 21, 8 * 8, 8 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLint(t, level);
    yagl_transport_put_out_GLint(t, xoffset);
    yagl_transport_put_out_GLint(t, yoffset);
    yagl_transport_put_out_GLint(t, x);
    yagl_transport_put_out_GLint(t, y);
    yagl_transport_put_out_GLsizei(t, width);
    yagl_transport_put_out_GLsizei(t, height);
    yagl_transport_end(t);
}

/*
 * glCullFace wrapper. id = 22
 */
void yagl_host_glCullFace(GLenum mode)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 22, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, mode);
    yagl_transport_end(t);
}

/*
 * glDeleteBuffers wrapper. id = 23
 */
void yagl_host_glDeleteBuffers(const GLuint *buffers, int32_t buffers_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 23, 2 * 8, 0 * 8 + yagl_transport_array_size(buffers, buffers_count, sizeof(GLuint)));
    yagl_transport_put_out_array(t, buffers, buffers_count, sizeof(GLuint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(buffers, buffers_count * sizeof(GLuint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glDeleteFramebuffers wrapper. id = 24
 */
void yagl_host_glDeleteFramebuffers(const GLuint *framebuffers, int32_t framebuffers_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 24, 2 * 8, 0 * 8 + yagl_transport_array_size(framebuffers, framebuffers_count, sizeof(GLuint)));
    yagl_transport_put_out_array(t, framebuffers, framebuffers_count, sizeof(GLuint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(framebuffers, framebuffers_count * sizeof(GLuint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glDeleteRenderbuffers wrapper. id = 25
 */
void yagl_host_glDeleteRenderbuffers(const GLuint *renderbuffers, int32_t renderbuffers_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 25, 2 * 8, 0 * 8 + yagl_transport_array_size(renderbuffers, renderbuffers_count, sizeof(GLuint)));
    yagl_transport_put_out_array(t, renderbuffers, renderbuffers_count, sizeof(GLuint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(renderbuffers, renderbuffers_count * sizeof(GLuint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glDeleteTextures wrapper. id = 26
 */
void yagl_host_glDeleteTextures(const GLuint *textures, int32_t textures_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 26, 2 * 8, 0 * 8 + yagl_transport_array_size(textures, textures_count, sizeof(GLuint)));
    yagl_transport_put_out_array(t, textures, textures_count, sizeof(GLuint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(textures, textures_count * sizeof(GLuint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glDepthFunc wrapper. id = 27
 */
void yagl_host_glDepthFunc(GLenum func)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 27, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, func);
    yagl_transport_end(t);
}

/*
 * glDepthMask wrapper. id = 28
 */
void yagl_host_glDepthMask(GLboolean flag)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 28, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLboolean(t, flag);
    yagl_transport_end(t);
}

/*
 * glDepthRangef wrapper. id = 29
 */
void yagl_host_glDepthRangef(GLclampf zNear, GLclampf zFar)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 29, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLclampf(t, zNear);
    yagl_transport_put_out_GLclampf(t, zFar);
    yagl_transport_end(t);
}

/*
 * glDisable wrapper. id = 30
 */
void yagl_host_glDisable(GLenum cap)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 30, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, cap);
    yagl_transport_end(t);
}

/*
 * glDrawArrays wrapper. id = 31
 */
void yagl_host_glDrawArrays(GLenum mode, GLint first, GLsizei count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 31, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, mode);
    yagl_transport_put_out_GLint(t, first);
    yagl_transport_put_out_GLsizei(t, count);
    yagl_transport_end(t);
}

/*
 * glEGLImageTargetTexture2DOES wrapper. id = 32
 */
void yagl_host_glEGLImageTargetTexture2DOES(GLenum target, yagl_host_handle image)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 32, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_yagl_host_handle(t, image);
    yagl_transport_end(t);
}

/*
 * glEnable wrapper. id = 33
 */
void yagl_host_glEnable(GLenum cap)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 33, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, cap);
    yagl_transport_end(t);
}

/*
 * glFlush wrapper. id = 34
 */
void yagl_host_glFlush()
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 34, 0 * 8, 0 * 8);
    yagl_transport_end(t);
    yagl_transport_sync(t);
}

/*
 * glFramebufferTexture2D wrapper. id = 35
 */
void yagl_host_glFramebufferTexture2D(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 35, 5 * 8, 5 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, attachment);
    yagl_transport_put_out_GLenum(t, textarget);
    yagl_transport_put_out_GLuint(t, texture);
    yagl_transport_put_out_GLint(t, level);
    yagl_transport_end(t);
}

/*
 * glFramebufferRenderbuffer wrapper. id = 36
 */
void yagl_host_glFramebufferRenderbuffer(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 36, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, attachment);
    yagl_transport_put_out_GLenum(t, renderbuffertarget);
    yagl_transport_put_out_GLuint(t, renderbuffer);
    yagl_transport_end(t);
}

/*
 * glFrontFace wrapper. id = 37
 */
void yagl_host_glFrontFace(GLenum mode)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 37, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, mode);
    yagl_transport_end(t);
}

/*
 * glGenBuffers wrapper. id = 38
 */
void yagl_host_glGenBuffers(GLuint *buffers, int32_t buffers_maxcount, int32_t *buffers_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 38, 2 * 8, 0 * 8 + yagl_transport_array_size(buffers, buffers_maxcount, sizeof(GLuint)));
    yagl_transport_put_in_array(t, buffers, buffers_maxcount, buffers_count, sizeof(GLuint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(buffers, buffers_maxcount * sizeof(GLuint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGenerateMipmap wrapper. id = 39
 */
void yagl_host_glGenerateMipmap(GLenum target)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 39, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_end(t);
}

/*
 * glGenFramebuffers wrapper. id = 40
 */
void yagl_host_glGenFramebuffers(GLuint *framebuffers, int32_t framebuffers_maxcount, int32_t *framebuffers_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 40, 2 * 8, 0 * 8 + yagl_transport_array_size(framebuffers, framebuffers_maxcount, sizeof(GLuint)));
    yagl_transport_put_in_array(t, framebuffers, framebuffers_maxcount, framebuffers_count, sizeof(GLuint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(framebuffers, framebuffers_maxcount * sizeof(GLuint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGenRenderbuffers wrapper. id = 41
 */
void yagl_host_glGenRenderbuffers(GLuint *renderbuffers, int32_t renderbuffers_maxcount, int32_t *renderbuffers_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 41, 2 * 8, 0 * 8 + yagl_transport_array_size(renderbuffers, renderbuffers_maxcount, sizeof(GLuint)));
    yagl_transport_put_in_array(t, renderbuffers, renderbuffers_maxcount, renderbuffers_count, sizeof(GLuint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(renderbuffers, renderbuffers_maxcount * sizeof(GLuint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGenTextures wrapper. id = 42
 */
void yagl_host_glGenTextures(GLuint *textures, int32_t textures_maxcount, int32_t *textures_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 42, 2 * 8, 0 * 8 + yagl_transport_array_size(textures, textures_maxcount, sizeof(GLuint)));
    yagl_transport_put_in_array(t, textures, textures_maxcount, textures_count, sizeof(GLuint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(textures, textures_maxcount * sizeof(GLuint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetBooleanv wrapper. id = 43
 */
void yagl_host_glGetBooleanv(GLenum pname, GLboolean *params, int32_t params_maxcount, int32_t *params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 43, 3 * 8, 1 * 8 + yagl_transport_array_size(params, params_maxcount, sizeof(GLboolean)));
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_array(t, params, params_maxcount, params_count, sizeof(GLboolean));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(params, params_maxcount * sizeof(GLboolean));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetBufferParameteriv wrapper. id = 44
 */
void yagl_host_glGetBufferParameteriv(GLenum target, GLenum pname, GLint *param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 44, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_GLint(t, param);
    yagl_transport_end(t);
}

/*
 * glGetError wrapper. id = 45
 */
GLenum yagl_host_glGetError()
{
    struct yagl_transport *t = yagl_get_transport();
    GLenum retval;

    yagl_transport_begin(t, yagl_api_id_gles1, 45, 2 * 8, 2 * 8);
    yagl_transport_put_in_GLenum(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * glGetFloatv wrapper. id = 46
 */
void yagl_host_glGetFloatv(GLenum pname, GLfloat *params, int32_t params_maxcount, int32_t *params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 46, 3 * 8, 1 * 8 + yagl_transport_array_size(params, params_maxcount, sizeof(GLfloat)));
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_array(t, params, params_maxcount, params_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(params, params_maxcount * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetFramebufferAttachmentParameteriv wrapper. id = 47
 */
void yagl_host_glGetFramebufferAttachmentParameteriv(GLenum target, GLenum attachment, GLenum pname, GLint *param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 47, 5 * 8, 5 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, attachment);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_GLint(t, param);
    yagl_transport_end(t);
}

/*
 * glGetIntegerv wrapper. id = 48
 */
void yagl_host_glGetIntegerv(GLenum pname, GLint *params, int32_t params_maxcount, int32_t *params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 48, 3 * 8, 1 * 8 + yagl_transport_array_size(params, params_maxcount, sizeof(GLint)));
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_array(t, params, params_maxcount, params_count, sizeof(GLint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(params, params_maxcount * sizeof(GLint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetRenderbufferParameteriv wrapper. id = 49
 */
void yagl_host_glGetRenderbufferParameteriv(GLenum target, GLenum pname, GLint *param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 49, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_GLint(t, param);
    yagl_transport_end(t);
}

/*
 * glGetTexParameterfv wrapper. id = 50
 */
void yagl_host_glGetTexParameterfv(GLenum target, GLenum pname, GLfloat *param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 50, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_GLfloat(t, param);
    yagl_transport_end(t);
}

/*
 * glGetTexParameteriv wrapper. id = 51
 */
void yagl_host_glGetTexParameteriv(GLenum target, GLenum pname, GLint *param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 51, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_GLint(t, param);
    yagl_transport_end(t);
}

/*
 * glHint wrapper. id = 52
 */
void yagl_host_glHint(GLenum target, GLenum mode)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 52, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, mode);
    yagl_transport_end(t);
}

/*
 * glIsBuffer wrapper. id = 53
 */
GLboolean yagl_host_glIsBuffer(GLuint buffer)
{
    struct yagl_transport *t = yagl_get_transport();
    GLboolean retval;

    yagl_transport_begin(t, yagl_api_id_gles1, 53, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLuint(t, buffer);
    yagl_transport_put_in_GLboolean(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * glIsEnabled wrapper. id = 54
 */
GLboolean yagl_host_glIsEnabled(GLenum cap)
{
    struct yagl_transport *t = yagl_get_transport();
    GLboolean retval;

    yagl_transport_begin(t, yagl_api_id_gles1, 54, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, cap);
    yagl_transport_put_in_GLboolean(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * glIsFramebuffer wrapper. id = 55
 */
GLboolean yagl_host_glIsFramebuffer(GLuint framebuffer)
{
    struct yagl_transport *t = yagl_get_transport();
    GLboolean retval;

    yagl_transport_begin(t, yagl_api_id_gles1, 55, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLuint(t, framebuffer);
    yagl_transport_put_in_GLboolean(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * glIsRenderbuffer wrapper. id = 56
 */
GLboolean yagl_host_glIsRenderbuffer(GLuint renderbuffer)
{
    struct yagl_transport *t = yagl_get_transport();
    GLboolean retval;

    yagl_transport_begin(t, yagl_api_id_gles1, 56, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLuint(t, renderbuffer);
    yagl_transport_put_in_GLboolean(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * glIsTexture wrapper. id = 57
 */
GLboolean yagl_host_glIsTexture(GLuint texture)
{
    struct yagl_transport *t = yagl_get_transport();
    GLboolean retval;

    yagl_transport_begin(t, yagl_api_id_gles1, 57, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLuint(t, texture);
    yagl_transport_put_in_GLboolean(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * glLineWidth wrapper. id = 58
 */
void yagl_host_glLineWidth(GLfloat width)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 58, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLfloat(t, width);
    yagl_transport_end(t);
}

/*
 * glPixelStorei wrapper. id = 59
 */
void yagl_host_glPixelStorei(GLenum pname, GLint param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 59, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_GLint(t, param);
    yagl_transport_end(t);
}

/*
 * glPolygonOffset wrapper. id = 60
 */
void yagl_host_glPolygonOffset(GLfloat factor, GLfloat units)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 60, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLfloat(t, factor);
    yagl_transport_put_out_GLfloat(t, units);
    yagl_transport_end(t);
}

/*
 * glReadPixels wrapper. id = 61
 */
void yagl_host_glReadPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels, int32_t pixels_maxcount, int32_t *pixels_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 61, 8 * 8, 6 * 8 + yagl_transport_array_size(pixels, pixels_maxcount, 1));
    yagl_transport_put_out_GLint(t, x);
    yagl_transport_put_out_GLint(t, y);
    yagl_transport_put_out_GLsizei(t, width);
    yagl_transport_put_out_GLsizei(t, height);
    yagl_transport_put_out_GLenum(t, format);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_in_array(t, pixels, pixels_maxcount, pixels_count, 1);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(pixels, pixels_maxcount * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glRenderbufferStorage wrapper. id = 62
 */
void yagl_host_glRenderbufferStorage(GLenum target, GLenum internalformat, GLsizei width, GLsizei height)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 62, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, internalformat);
    yagl_transport_put_out_GLsizei(t, width);
    yagl_transport_put_out_GLsizei(t, height);
    yagl_transport_end(t);
}

/*
 * glSampleCoverage wrapper. id = 63
 */
void yagl_host_glSampleCoverage(GLclampf value, GLboolean invert)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 63, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLclampf(t, value);
    yagl_transport_put_out_GLboolean(t, invert);
    yagl_transport_end(t);
}

/*
 * glScissor wrapper. id = 64
 */
void yagl_host_glScissor(GLint x, GLint y, GLsizei width, GLsizei height)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 64, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLint(t, x);
    yagl_transport_put_out_GLint(t, y);
    yagl_transport_put_out_GLsizei(t, width);
    yagl_transport_put_out_GLsizei(t, height);
    yagl_transport_end(t);
}

/*
 * glStencilFunc wrapper. id = 65
 */
void yagl_host_glStencilFunc(GLenum func, GLint ref, GLuint mask)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 65, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, func);
    yagl_transport_put_out_GLint(t, ref);
    yagl_transport_put_out_GLuint(t, mask);
    yagl_transport_end(t);
}

/*
 * glStencilMask wrapper. id = 66
 */
void yagl_host_glStencilMask(GLuint mask)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 66, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLuint(t, mask);
    yagl_transport_end(t);
}

/*
 * glStencilOp wrapper. id = 67
 */
void yagl_host_glStencilOp(GLenum fail, GLenum zfail, GLenum zpass)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 67, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, fail);
    yagl_transport_put_out_GLenum(t, zfail);
    yagl_transport_put_out_GLenum(t, zpass);
    yagl_transport_end(t);
}

/*
 * glTexImage2D wrapper. id = 68
 */
void yagl_host_glTexImage2D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels, int32_t pixels_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 68, 10 * 8, 8 * 8 + yagl_transport_array_size(pixels, pixels_count, 1));
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLint(t, level);
    yagl_transport_put_out_GLint(t, internalformat);
    yagl_transport_put_out_GLsizei(t, width);
    yagl_transport_put_out_GLsizei(t, height);
    yagl_transport_put_out_GLint(t, border);
    yagl_transport_put_out_GLenum(t, format);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_out_array(t, pixels, pixels_count, 1);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(pixels, pixels_count * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glTexParameterf wrapper. id = 69
 */
void yagl_host_glTexParameterf(GLenum target, GLenum pname, GLfloat param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 69, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_GLfloat(t, param);
    yagl_transport_end(t);
}

/*
 * glTexParameterfv wrapper. id = 70
 */
void yagl_host_glTexParameterfv(GLenum target, GLenum pname, const GLfloat *params, int32_t params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 70, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_array(t, params, params_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(params, params_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glTexParameteri wrapper. id = 71
 */
void yagl_host_glTexParameteri(GLenum target, GLenum pname, GLint param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 71, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_GLint(t, param);
    yagl_transport_end(t);
}

/*
 * glTexParameteriv wrapper. id = 72
 */
void yagl_host_glTexParameteriv(GLenum target, GLenum pname, const GLint *params, int32_t params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 72, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_count, sizeof(GLint)));
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_array(t, params, params_count, sizeof(GLint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(params, params_count * sizeof(GLint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glTexSubImage2D wrapper. id = 73
 */
void yagl_host_glTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels, int32_t pixels_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 73, 10 * 8, 8 * 8 + yagl_transport_array_size(pixels, pixels_count, 1));
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLint(t, level);
    yagl_transport_put_out_GLint(t, xoffset);
    yagl_transport_put_out_GLint(t, yoffset);
    yagl_transport_put_out_GLsizei(t, width);
    yagl_transport_put_out_GLsizei(t, height);
    yagl_transport_put_out_GLenum(t, format);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_out_array(t, pixels, pixels_count, 1);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(pixels, pixels_count * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glViewport wrapper. id = 74
 */
void yagl_host_glViewport(GLint x, GLint y, GLsizei width, GLsizei height)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 74, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLint(t, x);
    yagl_transport_put_out_GLint(t, y);
    yagl_transport_put_out_GLsizei(t, width);
    yagl_transport_put_out_GLsizei(t, height);
    yagl_transport_end(t);
}

/*
 * glTransferArrayYAGL wrapper. id = 75
 */
void yagl_host_glTransferArrayYAGL(GLuint indx, GLint first, const GLvoid *data, int32_t data_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 75, 4 * 8, 2 * 8 + yagl_transport_array_size(data, data_count, 1));
    yagl_transport_put_out_GLuint(t, indx);
    yagl_transport_put_out_GLint(t, first);
    yagl_transport_put_out_array(t, data, data_count, 1);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(data, data_count * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glDrawElementsIndicesYAGL wrapper. id = 76
 */
void yagl_host_glDrawElementsIndicesYAGL(GLenum mode, GLenum type, const GLvoid *indices, int32_t indices_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 76, 4 * 8, 2 * 8 + yagl_transport_array_size(indices, indices_count, 1));
    yagl_transport_put_out_GLenum(t, mode);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_out_array(t, indices, indices_count, 1);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(indices, indices_count * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glDrawElementsOffsetYAGL wrapper. id = 77
 */
void yagl_host_glDrawElementsOffsetYAGL(GLenum mode, GLenum type, GLsizei offset, GLsizei count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 77, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLenum(t, mode);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_out_GLsizei(t, offset);
    yagl_transport_put_out_GLsizei(t, count);
    yagl_transport_end(t);
}

/*
 * glGetExtensionStringYAGL wrapper. id = 78
 */
void yagl_host_glGetExtensionStringYAGL(GLchar *str, int32_t str_maxcount, int32_t *str_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 78, 2 * 8, 0 * 8 + yagl_transport_array_size(str, str_maxcount, sizeof(GLchar)));
    yagl_transport_put_in_array(t, str, str_maxcount, str_count, sizeof(GLchar));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(str, str_maxcount * sizeof(GLchar));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetVertexAttribRangeYAGL wrapper. id = 79
 */
void yagl_host_glGetVertexAttribRangeYAGL(GLenum type, GLsizei offset, GLsizei count, GLint *range_first, GLsizei *range_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 79, 7 * 8, 7 * 8);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_out_GLsizei(t, offset);
    yagl_transport_put_out_GLsizei(t, count);
    yagl_transport_put_in_GLint(t, range_first);
    yagl_transport_put_in_GLsizei(t, range_count);
    yagl_transport_end(t);
}

/*
 * glAlphaFunc wrapper. id = 80
 */
void yagl_host_glAlphaFunc(GLenum func, GLclampf ref)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 80, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, func);
    yagl_transport_put_out_GLclampf(t, ref);
    yagl_transport_end(t);
}

/*
 * glClipPlanef wrapper. id = 81
 */
void yagl_host_glClipPlanef(GLenum plane, const GLfloat *equation, int32_t equation_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 81, 3 * 8, 1 * 8 + yagl_transport_array_size(equation, equation_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLenum(t, plane);
    yagl_transport_put_out_array(t, equation, equation_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(equation, equation_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glColor4f wrapper. id = 82
 */
void yagl_host_glColor4f(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 82, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLfloat(t, red);
    yagl_transport_put_out_GLfloat(t, green);
    yagl_transport_put_out_GLfloat(t, blue);
    yagl_transport_put_out_GLfloat(t, alpha);
    yagl_transport_end(t);
}

/*
 * glFogf wrapper. id = 83
 */
void yagl_host_glFogf(GLenum pname, GLfloat param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 83, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_GLfloat(t, param);
    yagl_transport_end(t);
}

/*
 * glFogfv wrapper. id = 84
 */
void yagl_host_glFogfv(GLenum pname, const GLfloat *params, int32_t params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 84, 3 * 8, 1 * 8 + yagl_transport_array_size(params, params_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_array(t, params, params_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(params, params_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glFrustumf wrapper. id = 85
 */
void yagl_host_glFrustumf(GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 85, 6 * 8, 6 * 8);
    yagl_transport_put_out_GLfloat(t, left);
    yagl_transport_put_out_GLfloat(t, right);
    yagl_transport_put_out_GLfloat(t, bottom);
    yagl_transport_put_out_GLfloat(t, top);
    yagl_transport_put_out_GLfloat(t, zNear);
    yagl_transport_put_out_GLfloat(t, zFar);
    yagl_transport_end(t);
}

/*
 * glGetClipPlanef wrapper. id = 86
 */
void yagl_host_glGetClipPlanef(GLenum pname, GLfloat *eqn, int32_t eqn_maxcount, int32_t *eqn_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 86, 3 * 8, 1 * 8 + yagl_transport_array_size(eqn, eqn_maxcount, sizeof(GLfloat)));
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_array(t, eqn, eqn_maxcount, eqn_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(eqn, eqn_maxcount * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetLightfv wrapper. id = 87
 */
void yagl_host_glGetLightfv(GLenum light, GLenum pname, GLfloat *params, int32_t params_maxcount, int32_t *params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 87, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_maxcount, sizeof(GLfloat)));
    yagl_transport_put_out_GLenum(t, light);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_array(t, params, params_maxcount, params_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(params, params_maxcount * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetMaterialfv wrapper. id = 88
 */
void yagl_host_glGetMaterialfv(GLenum face, GLenum pname, GLfloat *params, int32_t params_maxcount, int32_t *params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 88, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_maxcount, sizeof(GLfloat)));
    yagl_transport_put_out_GLenum(t, face);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_array(t, params, params_maxcount, params_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(params, params_maxcount * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetTexEnvfv wrapper. id = 89
 */
void yagl_host_glGetTexEnvfv(GLenum env, GLenum pname, GLfloat *params, int32_t params_maxcount, int32_t *params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 89, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_maxcount, sizeof(GLfloat)));
    yagl_transport_put_out_GLenum(t, env);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_array(t, params, params_maxcount, params_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(params, params_maxcount * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glLightModelf wrapper. id = 90
 */
void yagl_host_glLightModelf(GLenum pname, GLfloat param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 90, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_GLfloat(t, param);
    yagl_transport_end(t);
}

/*
 * glLightModelfv wrapper. id = 91
 */
void yagl_host_glLightModelfv(GLenum pname, const GLfloat *params, int32_t params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 91, 3 * 8, 1 * 8 + yagl_transport_array_size(params, params_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_array(t, params, params_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(params, params_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glLightf wrapper. id = 92
 */
void yagl_host_glLightf(GLenum light, GLenum pname, GLfloat param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 92, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, light);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_GLfloat(t, param);
    yagl_transport_end(t);
}

/*
 * glLightfv wrapper. id = 93
 */
void yagl_host_glLightfv(GLenum light, GLenum pname, const GLfloat *params, int32_t params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 93, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLenum(t, light);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_array(t, params, params_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(params, params_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glLoadMatrixf wrapper. id = 94
 */
void yagl_host_glLoadMatrixf(const GLfloat *m, int32_t m_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 94, 2 * 8, 0 * 8 + yagl_transport_array_size(m, m_count, sizeof(GLfloat)));
    yagl_transport_put_out_array(t, m, m_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(m, m_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glMaterialf wrapper. id = 95
 */
void yagl_host_glMaterialf(GLenum face, GLenum pname, GLfloat param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 95, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, face);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_GLfloat(t, param);
    yagl_transport_end(t);
}

/*
 * glMaterialfv wrapper. id = 96
 */
void yagl_host_glMaterialfv(GLenum face, GLenum pname, const GLfloat *params, int32_t params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 96, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLenum(t, face);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_array(t, params, params_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(params, params_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glMultMatrixf wrapper. id = 97
 */
void yagl_host_glMultMatrixf(const GLfloat *m, int32_t m_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 97, 2 * 8, 0 * 8 + yagl_transport_array_size(m, m_count, sizeof(GLfloat)));
    yagl_transport_put_out_array(t, m, m_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(m, m_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glMultiTexCoord4f wrapper. id = 98
 */
void yagl_host_glMultiTexCoord4f(GLenum target, GLfloat s, GLfloat tt, GLfloat r, GLfloat q)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 98, 5 * 8, 5 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLfloat(t, s);
    yagl_transport_put_out_GLfloat(t, tt);
    yagl_transport_put_out_GLfloat(t, r);
    yagl_transport_put_out_GLfloat(t, q);
    yagl_transport_end(t);
}

/*
 * glNormal3f wrapper. id = 99
 */
void yagl_host_glNormal3f(GLfloat nx, GLfloat ny, GLfloat nz)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 99, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLfloat(t, nx);
    yagl_transport_put_out_GLfloat(t, ny);
    yagl_transport_put_out_GLfloat(t, nz);
    yagl_transport_end(t);
}

/*
 * glOrthof wrapper. id = 100
 */
void yagl_host_glOrthof(GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 100, 6 * 8, 6 * 8);
    yagl_transport_put_out_GLfloat(t, left);
    yagl_transport_put_out_GLfloat(t, right);
    yagl_transport_put_out_GLfloat(t, bottom);
    yagl_transport_put_out_GLfloat(t, top);
    yagl_transport_put_out_GLfloat(t, zNear);
    yagl_transport_put_out_GLfloat(t, zFar);
    yagl_transport_end(t);
}

/*
 * glPointParameterf wrapper. id = 101
 */
void yagl_host_glPointParameterf(GLenum pname, GLfloat param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 101, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_GLfloat(t, param);
    yagl_transport_end(t);
}

/*
 * glPointParameterfv wrapper. id = 102
 */
void yagl_host_glPointParameterfv(GLenum pname, const GLfloat *params, int32_t params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 102, 3 * 8, 1 * 8 + yagl_transport_array_size(params, params_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_array(t, params, params_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(params, params_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glPointSize wrapper. id = 103
 */
void yagl_host_glPointSize(GLfloat size)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 103, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLfloat(t, size);
    yagl_transport_end(t);
}

/*
 * glPointSizePointerOES wrapper. id = 104
 */
void yagl_host_glPointSizePointerOES(GLenum type, GLsizei stride, const GLvoid *pointer)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 104, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_out_GLsizei(t, stride);
    yagl_transport_put_out_va(t, pointer);
    yagl_transport_end(t);
}

/*
 * glRotatef wrapper. id = 105
 */
void yagl_host_glRotatef(GLfloat angle, GLfloat x, GLfloat y, GLfloat z)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 105, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLfloat(t, angle);
    yagl_transport_put_out_GLfloat(t, x);
    yagl_transport_put_out_GLfloat(t, y);
    yagl_transport_put_out_GLfloat(t, z);
    yagl_transport_end(t);
}

/*
 * glScalef wrapper. id = 106
 */
void yagl_host_glScalef(GLfloat x, GLfloat y, GLfloat z)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 106, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLfloat(t, x);
    yagl_transport_put_out_GLfloat(t, y);
    yagl_transport_put_out_GLfloat(t, z);
    yagl_transport_end(t);
}

/*
 * glTexEnvf wrapper. id = 107
 */
void yagl_host_glTexEnvf(GLenum target, GLenum pname, GLfloat param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 107, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_GLfloat(t, param);
    yagl_transport_end(t);
}

/*
 * glTexEnvfv wrapper. id = 108
 */
void yagl_host_glTexEnvfv(GLenum target, GLenum pname, const GLfloat *params, int32_t params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 108, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_array(t, params, params_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(params, params_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glTranslatef wrapper. id = 109
 */
void yagl_host_glTranslatef(GLfloat x, GLfloat y, GLfloat z)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 109, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLfloat(t, x);
    yagl_transport_put_out_GLfloat(t, y);
    yagl_transport_put_out_GLfloat(t, z);
    yagl_transport_end(t);
}

/*
 * glAlphaFuncx wrapper. id = 110
 */
void yagl_host_glAlphaFuncx(GLenum func, GLclampx ref)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 110, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, func);
    yagl_transport_put_out_GLclampx(t, ref);
    yagl_transport_end(t);
}

/*
 * glClearColorx wrapper. id = 111
 */
void yagl_host_glClearColorx(GLclampx red, GLclampx green, GLclampx blue, GLclampx alpha)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 111, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLclampx(t, red);
    yagl_transport_put_out_GLclampx(t, green);
    yagl_transport_put_out_GLclampx(t, blue);
    yagl_transport_put_out_GLclampx(t, alpha);
    yagl_transport_end(t);
}

/*
 * glClearDepthx wrapper. id = 112
 */
void yagl_host_glClearDepthx(GLclampx depth)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 112, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLclampx(t, depth);
    yagl_transport_end(t);
}

/*
 * glClientActiveTexture wrapper. id = 113
 */
void yagl_host_glClientActiveTexture(GLenum texture)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 113, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, texture);
    yagl_transport_end(t);
}

/*
 * glClipPlanex wrapper. id = 114
 */
void yagl_host_glClipPlanex(GLenum plane, const GLfixed *equation, int32_t equation_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 114, 3 * 8, 1 * 8 + yagl_transport_array_size(equation, equation_count, sizeof(GLfixed)));
    yagl_transport_put_out_GLenum(t, plane);
    yagl_transport_put_out_array(t, equation, equation_count, sizeof(GLfixed));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(equation, equation_count * sizeof(GLfixed));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glColor4ub wrapper. id = 115
 */
void yagl_host_glColor4ub(GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 115, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLubyte(t, red);
    yagl_transport_put_out_GLubyte(t, green);
    yagl_transport_put_out_GLubyte(t, blue);
    yagl_transport_put_out_GLubyte(t, alpha);
    yagl_transport_end(t);
}

/*
 * glColor4x wrapper. id = 116
 */
void yagl_host_glColor4x(GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 116, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLfixed(t, red);
    yagl_transport_put_out_GLfixed(t, green);
    yagl_transport_put_out_GLfixed(t, blue);
    yagl_transport_put_out_GLfixed(t, alpha);
    yagl_transport_end(t);
}

/*
 * glColorPointer wrapper. id = 117
 */
void yagl_host_glColorPointer(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 117, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLint(t, size);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_out_GLsizei(t, stride);
    yagl_transport_put_out_va(t, pointer);
    yagl_transport_end(t);
}

/*
 * glDepthRangex wrapper. id = 118
 */
void yagl_host_glDepthRangex(GLclampx zNear, GLclampx zFar)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 118, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLclampx(t, zNear);
    yagl_transport_put_out_GLclampx(t, zFar);
    yagl_transport_end(t);
}

/*
 * glDisableClientState wrapper. id = 119
 */
void yagl_host_glDisableClientState(GLenum array)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 119, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, array);
    yagl_transport_end(t);
}

/*
 * glEnableClientState wrapper. id = 120
 */
void yagl_host_glEnableClientState(GLenum array)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 120, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, array);
    yagl_transport_end(t);
}

/*
 * glFogx wrapper. id = 121
 */
void yagl_host_glFogx(GLenum pname, GLfixed param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 121, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_GLfixed(t, param);
    yagl_transport_end(t);
}

/*
 * glFogxv wrapper. id = 122
 */
void yagl_host_glFogxv(GLenum pname, const GLfixed *params, int32_t params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 122, 3 * 8, 1 * 8 + yagl_transport_array_size(params, params_count, sizeof(GLfixed)));
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_array(t, params, params_count, sizeof(GLfixed));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(params, params_count * sizeof(GLfixed));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glFrustumx wrapper. id = 123
 */
void yagl_host_glFrustumx(GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 123, 6 * 8, 6 * 8);
    yagl_transport_put_out_GLfixed(t, left);
    yagl_transport_put_out_GLfixed(t, right);
    yagl_transport_put_out_GLfixed(t, bottom);
    yagl_transport_put_out_GLfixed(t, top);
    yagl_transport_put_out_GLfixed(t, zNear);
    yagl_transport_put_out_GLfixed(t, zFar);
    yagl_transport_end(t);
}

/*
 * glGetClipPlanex wrapper. id = 124
 */
void yagl_host_glGetClipPlanex(GLenum pname, GLfixed *eqn, int32_t eqn_maxcount, int32_t *eqn_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 124, 3 * 8, 1 * 8 + yagl_transport_array_size(eqn, eqn_maxcount, sizeof(GLfixed)));
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_array(t, eqn, eqn_maxcount, eqn_count, sizeof(GLfixed));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(eqn, eqn_maxcount * sizeof(GLfixed));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetFixedv wrapper. id = 125
 */
void yagl_host_glGetFixedv(GLenum pname, GLfixed *params, int32_t params_maxcount, int32_t *params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 125, 3 * 8, 1 * 8 + yagl_transport_array_size(params, params_maxcount, sizeof(GLfixed)));
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_array(t, params, params_maxcount, params_count, sizeof(GLfixed));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(params, params_maxcount * sizeof(GLfixed));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetLightxv wrapper. id = 126
 */
void yagl_host_glGetLightxv(GLenum light, GLenum pname, GLfixed *params, int32_t params_maxcount, int32_t *params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 126, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_maxcount, sizeof(GLfixed)));
    yagl_transport_put_out_GLenum(t, light);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_array(t, params, params_maxcount, params_count, sizeof(GLfixed));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(params, params_maxcount * sizeof(GLfixed));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetMaterialxv wrapper. id = 127
 */
void yagl_host_glGetMaterialxv(GLenum face, GLenum pname, GLfixed *params, int32_t params_maxcount, int32_t *params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 127, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_maxcount, sizeof(GLfixed)));
    yagl_transport_put_out_GLenum(t, face);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_array(t, params, params_maxcount, params_count, sizeof(GLfixed));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(params, params_maxcount * sizeof(GLfixed));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetPointerv wrapper. id = 128
 */
void yagl_host_glGetPointerv(GLenum pname, GLvoid **params)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 128, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_va(t, (void**)params);
    yagl_transport_end(t);
}

/*
 * glGetTexEnviv wrapper. id = 129
 */
void yagl_host_glGetTexEnviv(GLenum env, GLenum pname, GLint *params, int32_t params_maxcount, int32_t *params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 129, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_maxcount, sizeof(GLint)));
    yagl_transport_put_out_GLenum(t, env);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_array(t, params, params_maxcount, params_count, sizeof(GLint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(params, params_maxcount * sizeof(GLint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetTexEnvxv wrapper. id = 130
 */
void yagl_host_glGetTexEnvxv(GLenum env, GLenum pname, GLfixed *params, int32_t params_maxcount, int32_t *params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 130, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_maxcount, sizeof(GLfixed)));
    yagl_transport_put_out_GLenum(t, env);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_array(t, params, params_maxcount, params_count, sizeof(GLfixed));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(params, params_maxcount * sizeof(GLfixed));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetTexParameterxv wrapper. id = 131
 */
void yagl_host_glGetTexParameterxv(GLenum target, GLenum pname, GLfixed *param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 131, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_GLfixed(t, param);
    yagl_transport_end(t);
}

/*
 * glLightModelx wrapper. id = 132
 */
void yagl_host_glLightModelx(GLenum pname, GLfixed param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 132, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_GLfixed(t, param);
    yagl_transport_end(t);
}

/*
 * glLightModelxv wrapper. id = 133
 */
void yagl_host_glLightModelxv(GLenum pname, const GLfixed *params, int32_t params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 133, 3 * 8, 1 * 8 + yagl_transport_array_size(params, params_count, sizeof(GLfixed)));
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_array(t, params, params_count, sizeof(GLfixed));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(params, params_count * sizeof(GLfixed));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glLightx wrapper. id = 134
 */
void yagl_host_glLightx(GLenum light, GLenum pname, GLfixed param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 134, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, light);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_GLfixed(t, param);
    yagl_transport_end(t);
}

/*
 * glLightxv wrapper. id = 135
 */
void yagl_host_glLightxv(GLenum light, GLenum pname, const GLfixed *params, int32_t params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 135, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_count, sizeof(GLfixed)));
    yagl_transport_put_out_GLenum(t, light);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_array(t, params, params_count, sizeof(GLfixed));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(params, params_count * sizeof(GLfixed));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glLineWidthx wrapper. id = 136
 */
void yagl_host_glLineWidthx(GLfixed width)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 136, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLfixed(t, width);
    yagl_transport_end(t);
}

/*
 * glLoadIdentity wrapper. id = 137
 */
void yagl_host_glLoadIdentity()
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 137, 0 * 8, 0 * 8);
    yagl_transport_end(t);
}

/*
 * glLoadMatrixx wrapper. id = 138
 */
void yagl_host_glLoadMatrixx(const GLfixed *m, int32_t m_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 138, 2 * 8, 0 * 8 + yagl_transport_array_size(m, m_count, sizeof(GLfixed)));
    yagl_transport_put_out_array(t, m, m_count, sizeof(GLfixed));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(m, m_count * sizeof(GLfixed));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glLogicOp wrapper. id = 139
 */
void yagl_host_glLogicOp(GLenum opcode)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 139, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, opcode);
    yagl_transport_end(t);
}

/*
 * glMaterialx wrapper. id = 140
 */
void yagl_host_glMaterialx(GLenum face, GLenum pname, GLfixed param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 140, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, face);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_GLfixed(t, param);
    yagl_transport_end(t);
}

/*
 * glMaterialxv wrapper. id = 141
 */
void yagl_host_glMaterialxv(GLenum face, GLenum pname, const GLfixed *params, int32_t params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 141, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_count, sizeof(GLfixed)));
    yagl_transport_put_out_GLenum(t, face);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_array(t, params, params_count, sizeof(GLfixed));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(params, params_count * sizeof(GLfixed));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glMatrixMode wrapper. id = 142
 */
void yagl_host_glMatrixMode(GLenum mode)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 142, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, mode);
    yagl_transport_end(t);
}

/*
 * glMultMatrixx wrapper. id = 143
 */
void yagl_host_glMultMatrixx(const GLfixed *m, int32_t m_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 143, 2 * 8, 0 * 8 + yagl_transport_array_size(m, m_count, sizeof(GLfixed)));
    yagl_transport_put_out_array(t, m, m_count, sizeof(GLfixed));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(m, m_count * sizeof(GLfixed));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glMultiTexCoord4x wrapper. id = 144
 */
void yagl_host_glMultiTexCoord4x(GLenum target, GLfixed s, GLfixed tt, GLfixed r, GLfixed q)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 144, 5 * 8, 5 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLfixed(t, s);
    yagl_transport_put_out_GLfixed(t, tt);
    yagl_transport_put_out_GLfixed(t, r);
    yagl_transport_put_out_GLfixed(t, q);
    yagl_transport_end(t);
}

/*
 * glNormal3x wrapper. id = 145
 */
void yagl_host_glNormal3x(GLfixed nx, GLfixed ny, GLfixed nz)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 145, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLfixed(t, nx);
    yagl_transport_put_out_GLfixed(t, ny);
    yagl_transport_put_out_GLfixed(t, nz);
    yagl_transport_end(t);
}

/*
 * glNormalPointer wrapper. id = 146
 */
void yagl_host_glNormalPointer(GLenum type, GLsizei stride, const GLvoid *pointer)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 146, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_out_GLsizei(t, stride);
    yagl_transport_put_out_va(t, pointer);
    yagl_transport_end(t);
}

/*
 * glOrthox wrapper. id = 147
 */
void yagl_host_glOrthox(GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 147, 6 * 8, 6 * 8);
    yagl_transport_put_out_GLfixed(t, left);
    yagl_transport_put_out_GLfixed(t, right);
    yagl_transport_put_out_GLfixed(t, bottom);
    yagl_transport_put_out_GLfixed(t, top);
    yagl_transport_put_out_GLfixed(t, zNear);
    yagl_transport_put_out_GLfixed(t, zFar);
    yagl_transport_end(t);
}

/*
 * glPointParameterx wrapper. id = 148
 */
void yagl_host_glPointParameterx(GLenum pname, GLfixed param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 148, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_GLfixed(t, param);
    yagl_transport_end(t);
}

/*
 * glPointParameterxv wrapper. id = 149
 */
void yagl_host_glPointParameterxv(GLenum pname, const GLfixed *params, int32_t params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 149, 3 * 8, 1 * 8 + yagl_transport_array_size(params, params_count, sizeof(GLfixed)));
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_array(t, params, params_count, sizeof(GLfixed));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(params, params_count * sizeof(GLfixed));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glPointSizex wrapper. id = 150
 */
void yagl_host_glPointSizex(GLfixed size)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 150, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLfixed(t, size);
    yagl_transport_end(t);
}

/*
 * glPolygonOffsetx wrapper. id = 151
 */
void yagl_host_glPolygonOffsetx(GLfixed factor, GLfixed units)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 151, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLfixed(t, factor);
    yagl_transport_put_out_GLfixed(t, units);
    yagl_transport_end(t);
}

/*
 * glPopMatrix wrapper. id = 152
 */
void yagl_host_glPopMatrix()
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 152, 0 * 8, 0 * 8);
    yagl_transport_end(t);
}

/*
 * glPushMatrix wrapper. id = 153
 */
void yagl_host_glPushMatrix()
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 153, 0 * 8, 0 * 8);
    yagl_transport_end(t);
}

/*
 * glRotatex wrapper. id = 154
 */
void yagl_host_glRotatex(GLfixed angle, GLfixed x, GLfixed y, GLfixed z)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 154, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLfixed(t, angle);
    yagl_transport_put_out_GLfixed(t, x);
    yagl_transport_put_out_GLfixed(t, y);
    yagl_transport_put_out_GLfixed(t, z);
    yagl_transport_end(t);
}

/*
 * glSampleCoveragex wrapper. id = 155
 */
void yagl_host_glSampleCoveragex(GLclampx value, GLboolean invert)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 155, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLclampx(t, value);
    yagl_transport_put_out_GLboolean(t, invert);
    yagl_transport_end(t);
}

/*
 * glScalex wrapper. id = 156
 */
void yagl_host_glScalex(GLfixed x, GLfixed y, GLfixed z)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 156, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLfixed(t, x);
    yagl_transport_put_out_GLfixed(t, y);
    yagl_transport_put_out_GLfixed(t, z);
    yagl_transport_end(t);
}

/*
 * glShadeModel wrapper. id = 157
 */
void yagl_host_glShadeModel(GLenum mode)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 157, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, mode);
    yagl_transport_end(t);
}

/*
 * glTexCoordPointer wrapper. id = 158
 */
void yagl_host_glTexCoordPointer(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 158, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLint(t, size);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_out_GLsizei(t, stride);
    yagl_transport_put_out_va(t, pointer);
    yagl_transport_end(t);
}

/*
 * glTexEnvi wrapper. id = 159
 */
void yagl_host_glTexEnvi(GLenum target, GLenum pname, GLint param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 159, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_GLint(t, param);
    yagl_transport_end(t);
}

/*
 * glTexEnvx wrapper. id = 160
 */
void yagl_host_glTexEnvx(GLenum target, GLenum pname, GLfixed param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 160, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_GLfixed(t, param);
    yagl_transport_end(t);
}

/*
 * glTexEnviv wrapper. id = 161
 */
void yagl_host_glTexEnviv(GLenum target, GLenum pname, const GLint *params, int32_t params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 161, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_count, sizeof(GLint)));
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_array(t, params, params_count, sizeof(GLint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(params, params_count * sizeof(GLint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glTexEnvxv wrapper. id = 162
 */
void yagl_host_glTexEnvxv(GLenum target, GLenum pname, const GLfixed *params, int32_t params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 162, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_count, sizeof(GLfixed)));
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_array(t, params, params_count, sizeof(GLfixed));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(params, params_count * sizeof(GLfixed));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glTexParameterx wrapper. id = 163
 */
void yagl_host_glTexParameterx(GLenum target, GLenum pname, GLfixed param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 163, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_GLfixed(t, param);
    yagl_transport_end(t);
}

/*
 * glTexParameterxv wrapper. id = 164
 */
void yagl_host_glTexParameterxv(GLenum target, GLenum pname, const GLfixed *params, int32_t params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 164, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_count, sizeof(GLfixed)));
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_array(t, params, params_count, sizeof(GLfixed));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(params, params_count * sizeof(GLfixed));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glTranslatex wrapper. id = 165
 */
void yagl_host_glTranslatex(GLfixed x, GLfixed y, GLfixed z)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 165, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLfixed(t, x);
    yagl_transport_put_out_GLfixed(t, y);
    yagl_transport_put_out_GLfixed(t, z);
    yagl_transport_end(t);
}

/*
 * glVertexPointer wrapper. id = 166
 */
void yagl_host_glVertexPointer(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles1, 166, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLint(t, size);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_out_GLsizei(t, stride);
    yagl_transport_put_out_va(t, pointer);
    yagl_transport_end(t);
}
