/*
 * Generated by gen-yagl-calls.py, do not modify!
 */
#include "yagl_host_gles2_calls.h"
#include "yagl_transport_gl2.h"
#include "yagl_state.h"
#include <assert.h>

/*
 * glActiveTexture wrapper. id = 1
 */
void yagl_host_glActiveTexture(GLenum texture)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 1, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, texture);
    yagl_transport_end(t);
}

/*
 * glBindBuffer wrapper. id = 2
 */
void yagl_host_glBindBuffer(GLenum target, GLuint buffer)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 2, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLuint(t, buffer);
    yagl_transport_end(t);
}

/*
 * glBindFramebuffer wrapper. id = 3
 */
void yagl_host_glBindFramebuffer(GLenum target, GLuint framebuffer)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 3, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLuint(t, framebuffer);
    yagl_transport_end(t);
}

/*
 * glBindRenderbuffer wrapper. id = 4
 */
void yagl_host_glBindRenderbuffer(GLenum target, GLuint renderbuffer)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 4, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLuint(t, renderbuffer);
    yagl_transport_end(t);
}

/*
 * glBindTexture wrapper. id = 5
 */
void yagl_host_glBindTexture(GLenum target, GLuint texture)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 5, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLuint(t, texture);
    yagl_transport_end(t);
}

/*
 * glBlendEquation wrapper. id = 6
 */
void yagl_host_glBlendEquation(GLenum mode)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 6, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, mode);
    yagl_transport_end(t);
}

/*
 * glBlendEquationSeparate wrapper. id = 7
 */
void yagl_host_glBlendEquationSeparate(GLenum modeRGB, GLenum modeAlpha)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 7, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, modeRGB);
    yagl_transport_put_out_GLenum(t, modeAlpha);
    yagl_transport_end(t);
}

/*
 * glBlendFunc wrapper. id = 8
 */
void yagl_host_glBlendFunc(GLenum sfactor, GLenum dfactor)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 8, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, sfactor);
    yagl_transport_put_out_GLenum(t, dfactor);
    yagl_transport_end(t);
}

/*
 * glBlendFuncSeparate wrapper. id = 9
 */
void yagl_host_glBlendFuncSeparate(GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 9, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLenum(t, srcRGB);
    yagl_transport_put_out_GLenum(t, dstRGB);
    yagl_transport_put_out_GLenum(t, srcAlpha);
    yagl_transport_put_out_GLenum(t, dstAlpha);
    yagl_transport_end(t);
}

/*
 * glBufferData wrapper. id = 10
 */
void yagl_host_glBufferData(GLenum target, const GLvoid *data, int32_t data_count, GLenum usage)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 10, 4 * 8, 2 * 8 + yagl_transport_array_size(data, data_count, 1));
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_array(t, data, data_count, 1);
    yagl_transport_put_out_GLenum(t, usage);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(data, data_count * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glBufferSubData wrapper. id = 11
 */
void yagl_host_glBufferSubData(GLenum target, GLsizei offset, const GLvoid *data, int32_t data_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 11, 4 * 8, 2 * 8 + yagl_transport_array_size(data, data_count, 1));
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLsizei(t, offset);
    yagl_transport_put_out_array(t, data, data_count, 1);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(data, data_count * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glCheckFramebufferStatus wrapper. id = 12
 */
GLenum yagl_host_glCheckFramebufferStatus(GLenum target)
{
    struct yagl_transport *t = yagl_get_transport();
    GLenum retval;

    yagl_transport_begin(t, yagl_api_id_gles2, 12, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_in_GLenum(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * glClear wrapper. id = 13
 */
void yagl_host_glClear(GLbitfield mask)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 13, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLbitfield(t, mask);
    yagl_transport_end(t);
}

/*
 * glClearColor wrapper. id = 14
 */
void yagl_host_glClearColor(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 14, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLclampf(t, red);
    yagl_transport_put_out_GLclampf(t, green);
    yagl_transport_put_out_GLclampf(t, blue);
    yagl_transport_put_out_GLclampf(t, alpha);
    yagl_transport_end(t);
}

/*
 * glClearDepthf wrapper. id = 15
 */
void yagl_host_glClearDepthf(GLclampf depth)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 15, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLclampf(t, depth);
    yagl_transport_end(t);
}

/*
 * glClearStencil wrapper. id = 16
 */
void yagl_host_glClearStencil(GLint s)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 16, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLint(t, s);
    yagl_transport_end(t);
}

/*
 * glColorMask wrapper. id = 17
 */
void yagl_host_glColorMask(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 17, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLboolean(t, red);
    yagl_transport_put_out_GLboolean(t, green);
    yagl_transport_put_out_GLboolean(t, blue);
    yagl_transport_put_out_GLboolean(t, alpha);
    yagl_transport_end(t);
}

/*
 * glCompressedTexImage2D wrapper. id = 18
 */
void yagl_host_glCompressedTexImage2D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, const GLvoid *data, int32_t data_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 18, 8 * 8, 6 * 8 + yagl_transport_array_size(data, data_count, 1));
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLint(t, level);
    yagl_transport_put_out_GLenum(t, internalformat);
    yagl_transport_put_out_GLsizei(t, width);
    yagl_transport_put_out_GLsizei(t, height);
    yagl_transport_put_out_GLint(t, border);
    yagl_transport_put_out_array(t, data, data_count, 1);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(data, data_count * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glCompressedTexSubImage2D wrapper. id = 19
 */
void yagl_host_glCompressedTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, const GLvoid *data, int32_t data_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 19, 9 * 8, 7 * 8 + yagl_transport_array_size(data, data_count, 1));
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLint(t, level);
    yagl_transport_put_out_GLint(t, xoffset);
    yagl_transport_put_out_GLint(t, yoffset);
    yagl_transport_put_out_GLsizei(t, width);
    yagl_transport_put_out_GLsizei(t, height);
    yagl_transport_put_out_GLenum(t, format);
    yagl_transport_put_out_array(t, data, data_count, 1);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(data, data_count * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glCopyTexImage2D wrapper. id = 20
 */
void yagl_host_glCopyTexImage2D(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 20, 8 * 8, 8 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLint(t, level);
    yagl_transport_put_out_GLenum(t, internalformat);
    yagl_transport_put_out_GLint(t, x);
    yagl_transport_put_out_GLint(t, y);
    yagl_transport_put_out_GLsizei(t, width);
    yagl_transport_put_out_GLsizei(t, height);
    yagl_transport_put_out_GLint(t, border);
    yagl_transport_end(t);
}

/*
 * glCopyTexSubImage2D wrapper. id = 21
 */
void yagl_host_glCopyTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 21, 8 * 8, 8 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLint(t, level);
    yagl_transport_put_out_GLint(t, xoffset);
    yagl_transport_put_out_GLint(t, yoffset);
    yagl_transport_put_out_GLint(t, x);
    yagl_transport_put_out_GLint(t, y);
    yagl_transport_put_out_GLsizei(t, width);
    yagl_transport_put_out_GLsizei(t, height);
    yagl_transport_end(t);
}

/*
 * glCullFace wrapper. id = 22
 */
void yagl_host_glCullFace(GLenum mode)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 22, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, mode);
    yagl_transport_end(t);
}

/*
 * glDeleteBuffers wrapper. id = 23
 */
void yagl_host_glDeleteBuffers(const GLuint *buffers, int32_t buffers_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 23, 2 * 8, 0 * 8 + yagl_transport_array_size(buffers, buffers_count, sizeof(GLuint)));
    yagl_transport_put_out_array(t, buffers, buffers_count, sizeof(GLuint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(buffers, buffers_count * sizeof(GLuint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glDeleteFramebuffers wrapper. id = 24
 */
void yagl_host_glDeleteFramebuffers(const GLuint *framebuffers, int32_t framebuffers_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 24, 2 * 8, 0 * 8 + yagl_transport_array_size(framebuffers, framebuffers_count, sizeof(GLuint)));
    yagl_transport_put_out_array(t, framebuffers, framebuffers_count, sizeof(GLuint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(framebuffers, framebuffers_count * sizeof(GLuint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glDeleteRenderbuffers wrapper. id = 25
 */
void yagl_host_glDeleteRenderbuffers(const GLuint *renderbuffers, int32_t renderbuffers_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 25, 2 * 8, 0 * 8 + yagl_transport_array_size(renderbuffers, renderbuffers_count, sizeof(GLuint)));
    yagl_transport_put_out_array(t, renderbuffers, renderbuffers_count, sizeof(GLuint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(renderbuffers, renderbuffers_count * sizeof(GLuint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glDeleteTextures wrapper. id = 26
 */
void yagl_host_glDeleteTextures(const GLuint *textures, int32_t textures_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 26, 2 * 8, 0 * 8 + yagl_transport_array_size(textures, textures_count, sizeof(GLuint)));
    yagl_transport_put_out_array(t, textures, textures_count, sizeof(GLuint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(textures, textures_count * sizeof(GLuint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glDepthFunc wrapper. id = 27
 */
void yagl_host_glDepthFunc(GLenum func)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 27, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, func);
    yagl_transport_end(t);
}

/*
 * glDepthMask wrapper. id = 28
 */
void yagl_host_glDepthMask(GLboolean flag)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 28, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLboolean(t, flag);
    yagl_transport_end(t);
}

/*
 * glDepthRangef wrapper. id = 29
 */
void yagl_host_glDepthRangef(GLclampf zNear, GLclampf zFar)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 29, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLclampf(t, zNear);
    yagl_transport_put_out_GLclampf(t, zFar);
    yagl_transport_end(t);
}

/*
 * glDisable wrapper. id = 30
 */
void yagl_host_glDisable(GLenum cap)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 30, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, cap);
    yagl_transport_end(t);
}

/*
 * glDrawArrays wrapper. id = 31
 */
void yagl_host_glDrawArrays(GLenum mode, GLint first, GLsizei count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 31, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, mode);
    yagl_transport_put_out_GLint(t, first);
    yagl_transport_put_out_GLsizei(t, count);
    yagl_transport_end(t);
}

/*
 * glEGLImageTargetTexture2DOES wrapper. id = 32
 */
void yagl_host_glEGLImageTargetTexture2DOES(GLenum target, yagl_host_handle image)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 32, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_yagl_host_handle(t, image);
    yagl_transport_end(t);
}

/*
 * glEnable wrapper. id = 33
 */
void yagl_host_glEnable(GLenum cap)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 33, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, cap);
    yagl_transport_end(t);
}

/*
 * glFlush wrapper. id = 34
 */
void yagl_host_glFlush()
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 34, 0 * 8, 0 * 8);
    yagl_transport_end(t);
    yagl_transport_sync(t);
}

/*
 * glFramebufferTexture2D wrapper. id = 35
 */
void yagl_host_glFramebufferTexture2D(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 35, 5 * 8, 5 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, attachment);
    yagl_transport_put_out_GLenum(t, textarget);
    yagl_transport_put_out_GLuint(t, texture);
    yagl_transport_put_out_GLint(t, level);
    yagl_transport_end(t);
}

/*
 * glFramebufferRenderbuffer wrapper. id = 36
 */
void yagl_host_glFramebufferRenderbuffer(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 36, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, attachment);
    yagl_transport_put_out_GLenum(t, renderbuffertarget);
    yagl_transport_put_out_GLuint(t, renderbuffer);
    yagl_transport_end(t);
}

/*
 * glFrontFace wrapper. id = 37
 */
void yagl_host_glFrontFace(GLenum mode)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 37, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, mode);
    yagl_transport_end(t);
}

/*
 * glGenBuffers wrapper. id = 38
 */
void yagl_host_glGenBuffers(GLuint *buffers, int32_t buffers_maxcount, int32_t *buffers_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 38, 2 * 8, 0 * 8 + yagl_transport_array_size(buffers, buffers_maxcount, sizeof(GLuint)));
    yagl_transport_put_in_array(t, buffers, buffers_maxcount, buffers_count, sizeof(GLuint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(buffers, buffers_maxcount * sizeof(GLuint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGenerateMipmap wrapper. id = 39
 */
void yagl_host_glGenerateMipmap(GLenum target)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 39, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_end(t);
}

/*
 * glGenFramebuffers wrapper. id = 40
 */
void yagl_host_glGenFramebuffers(GLuint *framebuffers, int32_t framebuffers_maxcount, int32_t *framebuffers_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 40, 2 * 8, 0 * 8 + yagl_transport_array_size(framebuffers, framebuffers_maxcount, sizeof(GLuint)));
    yagl_transport_put_in_array(t, framebuffers, framebuffers_maxcount, framebuffers_count, sizeof(GLuint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(framebuffers, framebuffers_maxcount * sizeof(GLuint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGenRenderbuffers wrapper. id = 41
 */
void yagl_host_glGenRenderbuffers(GLuint *renderbuffers, int32_t renderbuffers_maxcount, int32_t *renderbuffers_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 41, 2 * 8, 0 * 8 + yagl_transport_array_size(renderbuffers, renderbuffers_maxcount, sizeof(GLuint)));
    yagl_transport_put_in_array(t, renderbuffers, renderbuffers_maxcount, renderbuffers_count, sizeof(GLuint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(renderbuffers, renderbuffers_maxcount * sizeof(GLuint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGenTextures wrapper. id = 42
 */
void yagl_host_glGenTextures(GLuint *textures, int32_t textures_maxcount, int32_t *textures_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 42, 2 * 8, 0 * 8 + yagl_transport_array_size(textures, textures_maxcount, sizeof(GLuint)));
    yagl_transport_put_in_array(t, textures, textures_maxcount, textures_count, sizeof(GLuint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(textures, textures_maxcount * sizeof(GLuint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetBooleanv wrapper. id = 43
 */
void yagl_host_glGetBooleanv(GLenum pname, GLboolean *params, int32_t params_maxcount, int32_t *params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 43, 3 * 8, 1 * 8 + yagl_transport_array_size(params, params_maxcount, sizeof(GLboolean)));
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_array(t, params, params_maxcount, params_count, sizeof(GLboolean));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(params, params_maxcount * sizeof(GLboolean));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetBufferParameteriv wrapper. id = 44
 */
void yagl_host_glGetBufferParameteriv(GLenum target, GLenum pname, GLint *param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 44, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_GLint(t, param);
    yagl_transport_end(t);
}

/*
 * glGetError wrapper. id = 45
 */
GLenum yagl_host_glGetError()
{
    struct yagl_transport *t = yagl_get_transport();
    GLenum retval;

    yagl_transport_begin(t, yagl_api_id_gles2, 45, 2 * 8, 2 * 8);
    yagl_transport_put_in_GLenum(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * glGetFloatv wrapper. id = 46
 */
void yagl_host_glGetFloatv(GLenum pname, GLfloat *params, int32_t params_maxcount, int32_t *params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 46, 3 * 8, 1 * 8 + yagl_transport_array_size(params, params_maxcount, sizeof(GLfloat)));
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_array(t, params, params_maxcount, params_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(params, params_maxcount * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetFramebufferAttachmentParameteriv wrapper. id = 47
 */
void yagl_host_glGetFramebufferAttachmentParameteriv(GLenum target, GLenum attachment, GLenum pname, GLint *param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 47, 5 * 8, 5 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, attachment);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_GLint(t, param);
    yagl_transport_end(t);
}

/*
 * glGetIntegerv wrapper. id = 48
 */
void yagl_host_glGetIntegerv(GLenum pname, GLint *params, int32_t params_maxcount, int32_t *params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 48, 3 * 8, 1 * 8 + yagl_transport_array_size(params, params_maxcount, sizeof(GLint)));
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_array(t, params, params_maxcount, params_count, sizeof(GLint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(params, params_maxcount * sizeof(GLint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetRenderbufferParameteriv wrapper. id = 49
 */
void yagl_host_glGetRenderbufferParameteriv(GLenum target, GLenum pname, GLint *param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 49, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_GLint(t, param);
    yagl_transport_end(t);
}

/*
 * glGetTexParameterfv wrapper. id = 50
 */
void yagl_host_glGetTexParameterfv(GLenum target, GLenum pname, GLfloat *param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 50, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_GLfloat(t, param);
    yagl_transport_end(t);
}

/*
 * glGetTexParameteriv wrapper. id = 51
 */
void yagl_host_glGetTexParameteriv(GLenum target, GLenum pname, GLint *param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 51, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_GLint(t, param);
    yagl_transport_end(t);
}

/*
 * glHint wrapper. id = 52
 */
void yagl_host_glHint(GLenum target, GLenum mode)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 52, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, mode);
    yagl_transport_end(t);
}

/*
 * glIsBuffer wrapper. id = 53
 */
GLboolean yagl_host_glIsBuffer(GLuint buffer)
{
    struct yagl_transport *t = yagl_get_transport();
    GLboolean retval;

    yagl_transport_begin(t, yagl_api_id_gles2, 53, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLuint(t, buffer);
    yagl_transport_put_in_GLboolean(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * glIsEnabled wrapper. id = 54
 */
GLboolean yagl_host_glIsEnabled(GLenum cap)
{
    struct yagl_transport *t = yagl_get_transport();
    GLboolean retval;

    yagl_transport_begin(t, yagl_api_id_gles2, 54, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, cap);
    yagl_transport_put_in_GLboolean(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * glIsFramebuffer wrapper. id = 55
 */
GLboolean yagl_host_glIsFramebuffer(GLuint framebuffer)
{
    struct yagl_transport *t = yagl_get_transport();
    GLboolean retval;

    yagl_transport_begin(t, yagl_api_id_gles2, 55, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLuint(t, framebuffer);
    yagl_transport_put_in_GLboolean(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * glIsRenderbuffer wrapper. id = 56
 */
GLboolean yagl_host_glIsRenderbuffer(GLuint renderbuffer)
{
    struct yagl_transport *t = yagl_get_transport();
    GLboolean retval;

    yagl_transport_begin(t, yagl_api_id_gles2, 56, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLuint(t, renderbuffer);
    yagl_transport_put_in_GLboolean(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * glIsTexture wrapper. id = 57
 */
GLboolean yagl_host_glIsTexture(GLuint texture)
{
    struct yagl_transport *t = yagl_get_transport();
    GLboolean retval;

    yagl_transport_begin(t, yagl_api_id_gles2, 57, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLuint(t, texture);
    yagl_transport_put_in_GLboolean(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * glLineWidth wrapper. id = 58
 */
void yagl_host_glLineWidth(GLfloat width)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 58, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLfloat(t, width);
    yagl_transport_end(t);
}

/*
 * glPixelStorei wrapper. id = 59
 */
void yagl_host_glPixelStorei(GLenum pname, GLint param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 59, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_GLint(t, param);
    yagl_transport_end(t);
}

/*
 * glPolygonOffset wrapper. id = 60
 */
void yagl_host_glPolygonOffset(GLfloat factor, GLfloat units)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 60, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLfloat(t, factor);
    yagl_transport_put_out_GLfloat(t, units);
    yagl_transport_end(t);
}

/*
 * glReadPixels wrapper. id = 61
 */
void yagl_host_glReadPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels, int32_t pixels_maxcount, int32_t *pixels_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 61, 8 * 8, 6 * 8 + yagl_transport_array_size(pixels, pixels_maxcount, 1));
    yagl_transport_put_out_GLint(t, x);
    yagl_transport_put_out_GLint(t, y);
    yagl_transport_put_out_GLsizei(t, width);
    yagl_transport_put_out_GLsizei(t, height);
    yagl_transport_put_out_GLenum(t, format);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_in_array(t, pixels, pixels_maxcount, pixels_count, 1);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(pixels, pixels_maxcount * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glRenderbufferStorage wrapper. id = 62
 */
void yagl_host_glRenderbufferStorage(GLenum target, GLenum internalformat, GLsizei width, GLsizei height)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 62, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, internalformat);
    yagl_transport_put_out_GLsizei(t, width);
    yagl_transport_put_out_GLsizei(t, height);
    yagl_transport_end(t);
}

/*
 * glSampleCoverage wrapper. id = 63
 */
void yagl_host_glSampleCoverage(GLclampf value, GLboolean invert)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 63, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLclampf(t, value);
    yagl_transport_put_out_GLboolean(t, invert);
    yagl_transport_end(t);
}

/*
 * glScissor wrapper. id = 64
 */
void yagl_host_glScissor(GLint x, GLint y, GLsizei width, GLsizei height)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 64, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLint(t, x);
    yagl_transport_put_out_GLint(t, y);
    yagl_transport_put_out_GLsizei(t, width);
    yagl_transport_put_out_GLsizei(t, height);
    yagl_transport_end(t);
}

/*
 * glStencilFunc wrapper. id = 65
 */
void yagl_host_glStencilFunc(GLenum func, GLint ref, GLuint mask)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 65, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, func);
    yagl_transport_put_out_GLint(t, ref);
    yagl_transport_put_out_GLuint(t, mask);
    yagl_transport_end(t);
}

/*
 * glStencilMask wrapper. id = 66
 */
void yagl_host_glStencilMask(GLuint mask)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 66, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLuint(t, mask);
    yagl_transport_end(t);
}

/*
 * glStencilOp wrapper. id = 67
 */
void yagl_host_glStencilOp(GLenum fail, GLenum zfail, GLenum zpass)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 67, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, fail);
    yagl_transport_put_out_GLenum(t, zfail);
    yagl_transport_put_out_GLenum(t, zpass);
    yagl_transport_end(t);
}

/*
 * glTexImage2D wrapper. id = 68
 */
void yagl_host_glTexImage2D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels, int32_t pixels_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 68, 10 * 8, 8 * 8 + yagl_transport_array_size(pixels, pixels_count, 1));
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLint(t, level);
    yagl_transport_put_out_GLint(t, internalformat);
    yagl_transport_put_out_GLsizei(t, width);
    yagl_transport_put_out_GLsizei(t, height);
    yagl_transport_put_out_GLint(t, border);
    yagl_transport_put_out_GLenum(t, format);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_out_array(t, pixels, pixels_count, 1);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(pixels, pixels_count * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glTexParameterf wrapper. id = 69
 */
void yagl_host_glTexParameterf(GLenum target, GLenum pname, GLfloat param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 69, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_GLfloat(t, param);
    yagl_transport_end(t);
}

/*
 * glTexParameterfv wrapper. id = 70
 */
void yagl_host_glTexParameterfv(GLenum target, GLenum pname, const GLfloat *params, int32_t params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 70, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_array(t, params, params_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(params, params_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glTexParameteri wrapper. id = 71
 */
void yagl_host_glTexParameteri(GLenum target, GLenum pname, GLint param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 71, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_GLint(t, param);
    yagl_transport_end(t);
}

/*
 * glTexParameteriv wrapper. id = 72
 */
void yagl_host_glTexParameteriv(GLenum target, GLenum pname, const GLint *params, int32_t params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 72, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_count, sizeof(GLint)));
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_out_array(t, params, params_count, sizeof(GLint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(params, params_count * sizeof(GLint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glTexSubImage2D wrapper. id = 73
 */
void yagl_host_glTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels, int32_t pixels_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 73, 10 * 8, 8 * 8 + yagl_transport_array_size(pixels, pixels_count, 1));
    yagl_transport_put_out_GLenum(t, target);
    yagl_transport_put_out_GLint(t, level);
    yagl_transport_put_out_GLint(t, xoffset);
    yagl_transport_put_out_GLint(t, yoffset);
    yagl_transport_put_out_GLsizei(t, width);
    yagl_transport_put_out_GLsizei(t, height);
    yagl_transport_put_out_GLenum(t, format);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_out_array(t, pixels, pixels_count, 1);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(pixels, pixels_count * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glViewport wrapper. id = 74
 */
void yagl_host_glViewport(GLint x, GLint y, GLsizei width, GLsizei height)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 74, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLint(t, x);
    yagl_transport_put_out_GLint(t, y);
    yagl_transport_put_out_GLsizei(t, width);
    yagl_transport_put_out_GLsizei(t, height);
    yagl_transport_end(t);
}

/*
 * glTransferArrayYAGL wrapper. id = 75
 */
void yagl_host_glTransferArrayYAGL(GLuint indx, GLint first, const GLvoid *data, int32_t data_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 75, 4 * 8, 2 * 8 + yagl_transport_array_size(data, data_count, 1));
    yagl_transport_put_out_GLuint(t, indx);
    yagl_transport_put_out_GLint(t, first);
    yagl_transport_put_out_array(t, data, data_count, 1);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(data, data_count * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glDrawElementsIndicesYAGL wrapper. id = 76
 */
void yagl_host_glDrawElementsIndicesYAGL(GLenum mode, GLenum type, const GLvoid *indices, int32_t indices_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 76, 4 * 8, 2 * 8 + yagl_transport_array_size(indices, indices_count, 1));
    yagl_transport_put_out_GLenum(t, mode);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_out_array(t, indices, indices_count, 1);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(indices, indices_count * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glDrawElementsOffsetYAGL wrapper. id = 77
 */
void yagl_host_glDrawElementsOffsetYAGL(GLenum mode, GLenum type, GLsizei offset, GLsizei count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 77, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLenum(t, mode);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_out_GLsizei(t, offset);
    yagl_transport_put_out_GLsizei(t, count);
    yagl_transport_end(t);
}

/*
 * glGetExtensionStringYAGL wrapper. id = 78
 */
void yagl_host_glGetExtensionStringYAGL(GLchar *str, int32_t str_maxcount, int32_t *str_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 78, 2 * 8, 0 * 8 + yagl_transport_array_size(str, str_maxcount, sizeof(GLchar)));
    yagl_transport_put_in_array(t, str, str_maxcount, str_count, sizeof(GLchar));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(str, str_maxcount * sizeof(GLchar));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetVertexAttribRangeYAGL wrapper. id = 79
 */
void yagl_host_glGetVertexAttribRangeYAGL(GLenum type, GLsizei offset, GLsizei count, GLint *range_first, GLsizei *range_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 79, 7 * 8, 7 * 8);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_out_GLsizei(t, offset);
    yagl_transport_put_out_GLsizei(t, count);
    yagl_transport_put_in_GLint(t, range_first);
    yagl_transport_put_in_GLsizei(t, range_count);
    yagl_transport_end(t);
}

/*
 * glAttachShader wrapper. id = 80
 */
void yagl_host_glAttachShader(GLuint program, GLuint shader)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 80, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_put_out_GLuint(t, shader);
    yagl_transport_end(t);
}

/*
 * glBindAttribLocation wrapper. id = 81
 */
void yagl_host_glBindAttribLocation(GLuint program, GLuint index, const GLchar *name, int32_t name_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 81, 4 * 8, 2 * 8 + yagl_transport_array_size(name, name_count, sizeof(GLchar)));
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_put_out_GLuint(t, index);
    yagl_transport_put_out_array(t, name, name_count, sizeof(GLchar));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(name, name_count * sizeof(GLchar));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glBlendColor wrapper. id = 82
 */
void yagl_host_glBlendColor(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 82, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLclampf(t, red);
    yagl_transport_put_out_GLclampf(t, green);
    yagl_transport_put_out_GLclampf(t, blue);
    yagl_transport_put_out_GLclampf(t, alpha);
    yagl_transport_end(t);
}

/*
 * glCompileShader wrapper. id = 83
 */
void yagl_host_glCompileShader(GLuint shader)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 83, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLuint(t, shader);
    yagl_transport_end(t);
}

/*
 * glCreateProgram wrapper. id = 84
 */
GLuint yagl_host_glCreateProgram()
{
    struct yagl_transport *t = yagl_get_transport();
    GLuint retval;

    yagl_transport_begin(t, yagl_api_id_gles2, 84, 2 * 8, 2 * 8);
    yagl_transport_put_in_GLuint(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * glCreateShader wrapper. id = 85
 */
GLuint yagl_host_glCreateShader(GLenum type)
{
    struct yagl_transport *t = yagl_get_transport();
    GLuint retval;

    yagl_transport_begin(t, yagl_api_id_gles2, 85, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_in_GLuint(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * glDeleteProgram wrapper. id = 86
 */
void yagl_host_glDeleteProgram(GLuint program)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 86, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_end(t);
}

/*
 * glDeleteShader wrapper. id = 87
 */
void yagl_host_glDeleteShader(GLuint shader)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 87, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLuint(t, shader);
    yagl_transport_end(t);
}

/*
 * glDetachShader wrapper. id = 88
 */
void yagl_host_glDetachShader(GLuint program, GLuint shader)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 88, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_put_out_GLuint(t, shader);
    yagl_transport_end(t);
}

/*
 * glDisableVertexAttribArray wrapper. id = 89
 */
void yagl_host_glDisableVertexAttribArray(GLuint index)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 89, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLuint(t, index);
    yagl_transport_end(t);
}

/*
 * glEnableVertexAttribArray wrapper. id = 90
 */
void yagl_host_glEnableVertexAttribArray(GLuint index)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 90, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLuint(t, index);
    yagl_transport_end(t);
}

/*
 * glGetActiveAttrib wrapper. id = 91
 */
void yagl_host_glGetActiveAttrib(GLuint program, GLuint index, GLint *size, GLenum *type, GLchar *name, int32_t name_maxcount, int32_t *name_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 91, 8 * 8, 6 * 8 + yagl_transport_array_size(name, name_maxcount, sizeof(GLchar)));
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_put_out_GLuint(t, index);
    yagl_transport_put_in_GLint(t, size);
    yagl_transport_put_in_GLenum(t, type);
    yagl_transport_put_in_array(t, name, name_maxcount, name_count, sizeof(GLchar));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(name, name_maxcount * sizeof(GLchar));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetActiveUniform wrapper. id = 92
 */
void yagl_host_glGetActiveUniform(GLuint program, GLuint index, GLint *size, GLenum *type, GLchar *name, int32_t name_maxcount, int32_t *name_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 92, 8 * 8, 6 * 8 + yagl_transport_array_size(name, name_maxcount, sizeof(GLchar)));
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_put_out_GLuint(t, index);
    yagl_transport_put_in_GLint(t, size);
    yagl_transport_put_in_GLenum(t, type);
    yagl_transport_put_in_array(t, name, name_maxcount, name_count, sizeof(GLchar));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(name, name_maxcount * sizeof(GLchar));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetAttachedShaders wrapper. id = 93
 */
void yagl_host_glGetAttachedShaders(GLuint program, GLuint *shaders, int32_t shaders_maxcount, int32_t *shaders_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 93, 3 * 8, 1 * 8 + yagl_transport_array_size(shaders, shaders_maxcount, sizeof(GLuint)));
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_put_in_array(t, shaders, shaders_maxcount, shaders_count, sizeof(GLuint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(shaders, shaders_maxcount * sizeof(GLuint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetAttribLocation wrapper. id = 94
 */
int yagl_host_glGetAttribLocation(GLuint program, const GLchar *name, int32_t name_count)
{
    struct yagl_transport *t = yagl_get_transport();
    int retval;

    yagl_transport_begin(t, yagl_api_id_gles2, 94, 5 * 8, 3 * 8 + yagl_transport_array_size(name, name_count, sizeof(GLchar)));
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_put_out_array(t, name, name_count, sizeof(GLchar));
    yagl_transport_put_in_int(t, &retval);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(name, name_count * sizeof(GLchar));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }

    return retval;
}

/*
 * glGetProgramiv wrapper. id = 95
 */
void yagl_host_glGetProgramiv(GLuint program, GLenum pname, GLint *param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 95, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_GLint(t, param);
    yagl_transport_end(t);
}

/*
 * glGetProgramInfoLog wrapper. id = 96
 */
void yagl_host_glGetProgramInfoLog(GLuint program, GLchar *infolog, int32_t infolog_maxcount, int32_t *infolog_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 96, 3 * 8, 1 * 8 + yagl_transport_array_size(infolog, infolog_maxcount, sizeof(GLchar)));
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_put_in_array(t, infolog, infolog_maxcount, infolog_count, sizeof(GLchar));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(infolog, infolog_maxcount * sizeof(GLchar));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetShaderiv wrapper. id = 97
 */
void yagl_host_glGetShaderiv(GLuint shader, GLenum pname, GLint *param)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 97, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLuint(t, shader);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_GLint(t, param);
    yagl_transport_end(t);
}

/*
 * glGetShaderInfoLog wrapper. id = 98
 */
void yagl_host_glGetShaderInfoLog(GLuint shader, GLchar *infolog, int32_t infolog_maxcount, int32_t *infolog_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 98, 3 * 8, 1 * 8 + yagl_transport_array_size(infolog, infolog_maxcount, sizeof(GLchar)));
    yagl_transport_put_out_GLuint(t, shader);
    yagl_transport_put_in_array(t, infolog, infolog_maxcount, infolog_count, sizeof(GLchar));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(infolog, infolog_maxcount * sizeof(GLchar));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetShaderPrecisionFormat wrapper. id = 99
 */
void yagl_host_glGetShaderPrecisionFormat(GLenum shadertype, GLenum precisiontype, GLint *range, int32_t range_maxcount, int32_t *range_count, GLint *precision)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 99, 6 * 8, 4 * 8 + yagl_transport_array_size(range, range_maxcount, sizeof(GLint)));
    yagl_transport_put_out_GLenum(t, shadertype);
    yagl_transport_put_out_GLenum(t, precisiontype);
    yagl_transport_put_in_array(t, range, range_maxcount, range_count, sizeof(GLint));
    yagl_transport_put_in_GLint(t, precision);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(range, range_maxcount * sizeof(GLint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetShaderSource wrapper. id = 100
 */
void yagl_host_glGetShaderSource(GLuint shader, GLchar *source, int32_t source_maxcount, int32_t *source_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 100, 3 * 8, 1 * 8 + yagl_transport_array_size(source, source_maxcount, sizeof(GLchar)));
    yagl_transport_put_out_GLuint(t, shader);
    yagl_transport_put_in_array(t, source, source_maxcount, source_count, sizeof(GLchar));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(source, source_maxcount * sizeof(GLchar));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetUniformfv wrapper. id = 101
 */
void yagl_host_glGetUniformfv(GLuint program, GLint location, GLfloat *params, int32_t params_maxcount, int32_t *params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 101, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_maxcount, sizeof(GLfloat)));
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_put_out_GLint(t, location);
    yagl_transport_put_in_array(t, params, params_maxcount, params_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(params, params_maxcount * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetUniformiv wrapper. id = 102
 */
void yagl_host_glGetUniformiv(GLuint program, GLint location, GLint *params, int32_t params_maxcount, int32_t *params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 102, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_maxcount, sizeof(GLint)));
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_put_out_GLint(t, location);
    yagl_transport_put_in_array(t, params, params_maxcount, params_count, sizeof(GLint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(params, params_maxcount * sizeof(GLint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetUniformLocation wrapper. id = 103
 */
int yagl_host_glGetUniformLocation(GLuint program, const GLchar *name, int32_t name_count)
{
    struct yagl_transport *t = yagl_get_transport();
    int retval;

    yagl_transport_begin(t, yagl_api_id_gles2, 103, 5 * 8, 3 * 8 + yagl_transport_array_size(name, name_count, sizeof(GLchar)));
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_put_out_array(t, name, name_count, sizeof(GLchar));
    yagl_transport_put_in_int(t, &retval);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(name, name_count * sizeof(GLchar));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }

    return retval;
}

/*
 * glGetVertexAttribfv wrapper. id = 104
 */
void yagl_host_glGetVertexAttribfv(GLuint index, GLenum pname, GLfloat *params, int32_t params_maxcount, int32_t *params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 104, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_maxcount, sizeof(GLfloat)));
    yagl_transport_put_out_GLuint(t, index);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_array(t, params, params_maxcount, params_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(params, params_maxcount * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetVertexAttribiv wrapper. id = 105
 */
void yagl_host_glGetVertexAttribiv(GLuint index, GLenum pname, GLint *params, int32_t params_maxcount, int32_t *params_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 105, 4 * 8, 2 * 8 + yagl_transport_array_size(params, params_maxcount, sizeof(GLint)));
    yagl_transport_put_out_GLuint(t, index);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_array(t, params, params_maxcount, params_count, sizeof(GLint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_write(params, params_maxcount * sizeof(GLint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glGetVertexAttribPointerv wrapper. id = 106
 */
void yagl_host_glGetVertexAttribPointerv(GLuint index, GLenum pname, GLvoid **pointer)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 106, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLuint(t, index);
    yagl_transport_put_out_GLenum(t, pname);
    yagl_transport_put_in_va(t, (void**)pointer);
    yagl_transport_end(t);
}

/*
 * glIsProgram wrapper. id = 107
 */
GLboolean yagl_host_glIsProgram(GLuint program)
{
    struct yagl_transport *t = yagl_get_transport();
    GLboolean retval;

    yagl_transport_begin(t, yagl_api_id_gles2, 107, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_put_in_GLboolean(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * glIsShader wrapper. id = 108
 */
GLboolean yagl_host_glIsShader(GLuint shader)
{
    struct yagl_transport *t = yagl_get_transport();
    GLboolean retval;

    yagl_transport_begin(t, yagl_api_id_gles2, 108, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLuint(t, shader);
    yagl_transport_put_in_GLboolean(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * glLinkProgram wrapper. id = 109
 */
void yagl_host_glLinkProgram(GLuint program)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 109, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_end(t);
}

/*
 * glReleaseShaderCompiler wrapper. id = 110
 */
void yagl_host_glReleaseShaderCompiler()
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 110, 0 * 8, 0 * 8);
    yagl_transport_end(t);
}

/*
 * glShaderBinary wrapper. id = 111
 */
void yagl_host_glShaderBinary(const GLuint *shaders, int32_t shaders_count, GLenum binaryformat, const GLvoid *binary, int32_t binary_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 111, 5 * 8, 1 * 8 + yagl_transport_array_size(shaders, shaders_count, sizeof(GLuint)) + yagl_transport_array_size(binary, binary_count, 1));
    yagl_transport_put_out_array(t, shaders, shaders_count, sizeof(GLuint));
    yagl_transport_put_out_GLenum(t, binaryformat);
    yagl_transport_put_out_array(t, binary, binary_count, 1);
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(shaders, shaders_count * sizeof(GLuint));
            yagl_transport_probe_read(binary, binary_count * 1);
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glShaderSource wrapper. id = 112
 */
void yagl_host_glShaderSource(GLuint shader, const GLchar *string, int32_t string_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 112, 3 * 8, 1 * 8 + yagl_transport_array_size(string, string_count, sizeof(GLchar)));
    yagl_transport_put_out_GLuint(t, shader);
    yagl_transport_put_out_array(t, string, string_count, sizeof(GLchar));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(string, string_count * sizeof(GLchar));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glStencilFuncSeparate wrapper. id = 113
 */
void yagl_host_glStencilFuncSeparate(GLenum face, GLenum func, GLint ref, GLuint mask)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 113, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLenum(t, face);
    yagl_transport_put_out_GLenum(t, func);
    yagl_transport_put_out_GLint(t, ref);
    yagl_transport_put_out_GLuint(t, mask);
    yagl_transport_end(t);
}

/*
 * glStencilMaskSeparate wrapper. id = 114
 */
void yagl_host_glStencilMaskSeparate(GLenum face, GLuint mask)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 114, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLenum(t, face);
    yagl_transport_put_out_GLuint(t, mask);
    yagl_transport_end(t);
}

/*
 * glStencilOpSeparate wrapper. id = 115
 */
void yagl_host_glStencilOpSeparate(GLenum face, GLenum fail, GLenum zfail, GLenum zpass)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 115, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLenum(t, face);
    yagl_transport_put_out_GLenum(t, fail);
    yagl_transport_put_out_GLenum(t, zfail);
    yagl_transport_put_out_GLenum(t, zpass);
    yagl_transport_end(t);
}

/*
 * glUniform1f wrapper. id = 116
 */
void yagl_host_glUniform1f(GLint location, GLfloat x)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 116, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLint(t, location);
    yagl_transport_put_out_GLfloat(t, x);
    yagl_transport_end(t);
}

/*
 * glUniform1fv wrapper. id = 117
 */
void yagl_host_glUniform1fv(GLint location, const GLfloat *v, int32_t v_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 117, 3 * 8, 1 * 8 + yagl_transport_array_size(v, v_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLint(t, location);
    yagl_transport_put_out_array(t, v, v_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(v, v_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glUniform1i wrapper. id = 118
 */
void yagl_host_glUniform1i(GLint location, GLint x)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 118, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLint(t, location);
    yagl_transport_put_out_GLint(t, x);
    yagl_transport_end(t);
}

/*
 * glUniform1iv wrapper. id = 119
 */
void yagl_host_glUniform1iv(GLint location, const GLint *v, int32_t v_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 119, 3 * 8, 1 * 8 + yagl_transport_array_size(v, v_count, sizeof(GLint)));
    yagl_transport_put_out_GLint(t, location);
    yagl_transport_put_out_array(t, v, v_count, sizeof(GLint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(v, v_count * sizeof(GLint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glUniform2f wrapper. id = 120
 */
void yagl_host_glUniform2f(GLint location, GLfloat x, GLfloat y)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 120, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLint(t, location);
    yagl_transport_put_out_GLfloat(t, x);
    yagl_transport_put_out_GLfloat(t, y);
    yagl_transport_end(t);
}

/*
 * glUniform2fv wrapper. id = 121
 */
void yagl_host_glUniform2fv(GLint location, const GLfloat *v, int32_t v_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 121, 3 * 8, 1 * 8 + yagl_transport_array_size(v, v_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLint(t, location);
    yagl_transport_put_out_array(t, v, v_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(v, v_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glUniform2i wrapper. id = 122
 */
void yagl_host_glUniform2i(GLint location, GLint x, GLint y)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 122, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLint(t, location);
    yagl_transport_put_out_GLint(t, x);
    yagl_transport_put_out_GLint(t, y);
    yagl_transport_end(t);
}

/*
 * glUniform2iv wrapper. id = 123
 */
void yagl_host_glUniform2iv(GLint location, const GLint *v, int32_t v_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 123, 3 * 8, 1 * 8 + yagl_transport_array_size(v, v_count, sizeof(GLint)));
    yagl_transport_put_out_GLint(t, location);
    yagl_transport_put_out_array(t, v, v_count, sizeof(GLint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(v, v_count * sizeof(GLint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glUniform3f wrapper. id = 124
 */
void yagl_host_glUniform3f(GLint location, GLfloat x, GLfloat y, GLfloat z)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 124, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLint(t, location);
    yagl_transport_put_out_GLfloat(t, x);
    yagl_transport_put_out_GLfloat(t, y);
    yagl_transport_put_out_GLfloat(t, z);
    yagl_transport_end(t);
}

/*
 * glUniform3fv wrapper. id = 125
 */
void yagl_host_glUniform3fv(GLint location, const GLfloat *v, int32_t v_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 125, 3 * 8, 1 * 8 + yagl_transport_array_size(v, v_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLint(t, location);
    yagl_transport_put_out_array(t, v, v_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(v, v_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glUniform3i wrapper. id = 126
 */
void yagl_host_glUniform3i(GLint location, GLint x, GLint y, GLint z)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 126, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLint(t, location);
    yagl_transport_put_out_GLint(t, x);
    yagl_transport_put_out_GLint(t, y);
    yagl_transport_put_out_GLint(t, z);
    yagl_transport_end(t);
}

/*
 * glUniform3iv wrapper. id = 127
 */
void yagl_host_glUniform3iv(GLint location, const GLint *v, int32_t v_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 127, 3 * 8, 1 * 8 + yagl_transport_array_size(v, v_count, sizeof(GLint)));
    yagl_transport_put_out_GLint(t, location);
    yagl_transport_put_out_array(t, v, v_count, sizeof(GLint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(v, v_count * sizeof(GLint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glUniform4f wrapper. id = 128
 */
void yagl_host_glUniform4f(GLint location, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 128, 5 * 8, 5 * 8);
    yagl_transport_put_out_GLint(t, location);
    yagl_transport_put_out_GLfloat(t, x);
    yagl_transport_put_out_GLfloat(t, y);
    yagl_transport_put_out_GLfloat(t, z);
    yagl_transport_put_out_GLfloat(t, w);
    yagl_transport_end(t);
}

/*
 * glUniform4fv wrapper. id = 129
 */
void yagl_host_glUniform4fv(GLint location, const GLfloat *v, int32_t v_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 129, 3 * 8, 1 * 8 + yagl_transport_array_size(v, v_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLint(t, location);
    yagl_transport_put_out_array(t, v, v_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(v, v_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glUniform4i wrapper. id = 130
 */
void yagl_host_glUniform4i(GLint location, GLint x, GLint y, GLint z, GLint w)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 130, 5 * 8, 5 * 8);
    yagl_transport_put_out_GLint(t, location);
    yagl_transport_put_out_GLint(t, x);
    yagl_transport_put_out_GLint(t, y);
    yagl_transport_put_out_GLint(t, z);
    yagl_transport_put_out_GLint(t, w);
    yagl_transport_end(t);
}

/*
 * glUniform4iv wrapper. id = 131
 */
void yagl_host_glUniform4iv(GLint location, const GLint *v, int32_t v_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 131, 3 * 8, 1 * 8 + yagl_transport_array_size(v, v_count, sizeof(GLint)));
    yagl_transport_put_out_GLint(t, location);
    yagl_transport_put_out_array(t, v, v_count, sizeof(GLint));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(v, v_count * sizeof(GLint));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glUniformMatrix2fv wrapper. id = 132
 */
void yagl_host_glUniformMatrix2fv(GLint location, GLboolean transpose, const GLfloat *value, int32_t value_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 132, 4 * 8, 2 * 8 + yagl_transport_array_size(value, value_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLint(t, location);
    yagl_transport_put_out_GLboolean(t, transpose);
    yagl_transport_put_out_array(t, value, value_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(value, value_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glUniformMatrix3fv wrapper. id = 133
 */
void yagl_host_glUniformMatrix3fv(GLint location, GLboolean transpose, const GLfloat *value, int32_t value_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 133, 4 * 8, 2 * 8 + yagl_transport_array_size(value, value_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLint(t, location);
    yagl_transport_put_out_GLboolean(t, transpose);
    yagl_transport_put_out_array(t, value, value_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(value, value_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glUniformMatrix4fv wrapper. id = 134
 */
void yagl_host_glUniformMatrix4fv(GLint location, GLboolean transpose, const GLfloat *value, int32_t value_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 134, 4 * 8, 2 * 8 + yagl_transport_array_size(value, value_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLint(t, location);
    yagl_transport_put_out_GLboolean(t, transpose);
    yagl_transport_put_out_array(t, value, value_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(value, value_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glUseProgram wrapper. id = 135
 */
void yagl_host_glUseProgram(GLuint program)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 135, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_end(t);
}

/*
 * glValidateProgram wrapper. id = 136
 */
void yagl_host_glValidateProgram(GLuint program)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 136, 1 * 8, 1 * 8);
    yagl_transport_put_out_GLuint(t, program);
    yagl_transport_end(t);
}

/*
 * glVertexAttrib1f wrapper. id = 137
 */
void yagl_host_glVertexAttrib1f(GLuint indx, GLfloat x)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 137, 2 * 8, 2 * 8);
    yagl_transport_put_out_GLuint(t, indx);
    yagl_transport_put_out_GLfloat(t, x);
    yagl_transport_end(t);
}

/*
 * glVertexAttrib1fv wrapper. id = 138
 */
void yagl_host_glVertexAttrib1fv(GLuint indx, const GLfloat *values, int32_t values_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 138, 3 * 8, 1 * 8 + yagl_transport_array_size(values, values_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLuint(t, indx);
    yagl_transport_put_out_array(t, values, values_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(values, values_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glVertexAttrib2f wrapper. id = 139
 */
void yagl_host_glVertexAttrib2f(GLuint indx, GLfloat x, GLfloat y)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 139, 3 * 8, 3 * 8);
    yagl_transport_put_out_GLuint(t, indx);
    yagl_transport_put_out_GLfloat(t, x);
    yagl_transport_put_out_GLfloat(t, y);
    yagl_transport_end(t);
}

/*
 * glVertexAttrib2fv wrapper. id = 140
 */
void yagl_host_glVertexAttrib2fv(GLuint indx, const GLfloat *values, int32_t values_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 140, 3 * 8, 1 * 8 + yagl_transport_array_size(values, values_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLuint(t, indx);
    yagl_transport_put_out_array(t, values, values_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(values, values_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glVertexAttrib3f wrapper. id = 141
 */
void yagl_host_glVertexAttrib3f(GLuint indx, GLfloat x, GLfloat y, GLfloat z)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 141, 4 * 8, 4 * 8);
    yagl_transport_put_out_GLuint(t, indx);
    yagl_transport_put_out_GLfloat(t, x);
    yagl_transport_put_out_GLfloat(t, y);
    yagl_transport_put_out_GLfloat(t, z);
    yagl_transport_end(t);
}

/*
 * glVertexAttrib3fv wrapper. id = 142
 */
void yagl_host_glVertexAttrib3fv(GLuint indx, const GLfloat *values, int32_t values_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 142, 3 * 8, 1 * 8 + yagl_transport_array_size(values, values_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLuint(t, indx);
    yagl_transport_put_out_array(t, values, values_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(values, values_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glVertexAttrib4f wrapper. id = 143
 */
void yagl_host_glVertexAttrib4f(GLuint indx, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 143, 5 * 8, 5 * 8);
    yagl_transport_put_out_GLuint(t, indx);
    yagl_transport_put_out_GLfloat(t, x);
    yagl_transport_put_out_GLfloat(t, y);
    yagl_transport_put_out_GLfloat(t, z);
    yagl_transport_put_out_GLfloat(t, w);
    yagl_transport_end(t);
}

/*
 * glVertexAttrib4fv wrapper. id = 144
 */
void yagl_host_glVertexAttrib4fv(GLuint indx, const GLfloat *values, int32_t values_count)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 144, 3 * 8, 1 * 8 + yagl_transport_array_size(values, values_count, sizeof(GLfloat)));
    yagl_transport_put_out_GLuint(t, indx);
    yagl_transport_put_out_array(t, values, values_count, sizeof(GLfloat));
    if (yagl_transport_direct(t)) {
        do {
            yagl_transport_probe_read(values, values_count * sizeof(GLfloat));
        } while (!yagl_transport_end(t));
    } else {
        yagl_transport_end(t);
    }
}

/*
 * glVertexAttribPointer wrapper. id = 145
 */
void yagl_host_glVertexAttribPointer(GLuint indx, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const GLvoid *ptr)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_gles2, 145, 6 * 8, 6 * 8);
    yagl_transport_put_out_GLuint(t, indx);
    yagl_transport_put_out_GLint(t, size);
    yagl_transport_put_out_GLenum(t, type);
    yagl_transport_put_out_GLboolean(t, normalized);
    yagl_transport_put_out_GLsizei(t, stride);
    yagl_transport_put_out_va(t, ptr);
    yagl_transport_end(t);
}
